=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SimplebillyApi::CustomerCommunicationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomerCommunicationApi' do
  before do
    # run before each test
    @api_instance = SimplebillyApi::CustomerCommunicationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerCommunicationApi' do
    it 'should create an instance of CustomerCommunicationApi' do
      expect(@api_instance).to be_instance_of(SimplebillyApi::CustomerCommunicationApi)
    end
  end

  # unit tests for create_communication
  # @param customer_communication_create 
  # @param [Hash] opts the optional parameters
  # @return [CustomerCommunication]
  describe 'create_communication test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for customercommunication_restore
  # @param communication_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomerCommunication]
  describe 'customercommunication_restore test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_communication
  # @param communication_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_communication test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_communication
  # @param communication_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomerCommunication]
  describe 'get_communication test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_contact_history
  # @param contact_id 
  # @param [Hash] opts the optional parameters
  # @return [ContactHistoryResponse]
  describe 'get_contact_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_communications
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [String] :contact_id Filter history to a single contact.
  # @option opts [CommunicationChannel] :channel 
  # @option opts [CommunicationDirection] :direction 
  # @option opts [Date] :from Only include communications after this ISO date (inclusive).
  # @option opts [Date] :to Only include communications before this ISO date (inclusive).
  # @return [Array<CustomerCommunication>]
  describe 'list_communications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_communication
  # @param communication_id 
  # @param customer_communication_update 
  # @param [Hash] opts the optional parameters
  # @return [CustomerCommunication]
  describe 'update_communication test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
