=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SimplebillyApi::GobdExportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GobdExportApi' do
  before do
    # run before each test
    @api_instance = SimplebillyApi::GobdExportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GobdExportApi' do
    it 'should create an instance of GobdExportApi' do
      expect(@api_instance).to be_instance_of(SimplebillyApi::GobdExportApi)
    end
  end

  # unit tests for buchhalter_csv_api
  # @param date_from 
  # @param date_to 
  # @param [Hash] opts the optional parameters
  # @return [GoBDExportResponse]
  describe 'buchhalter_csv_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for gobd_export_api
  # GoBD/GDPdU export. Default: ZIP archive (&#x60;index.xml&#x60; + CSV tables, IDEA format). &#x60;?format&#x3D;csv&#x60; returns the legacy single-journal CSV as JSON.
  # @param year 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :format Export format: &#x60;zip&#x60; (default, full GDPdU/IDEA export) or &#x60;csv&#x60; (legacy single-journal CSV as JSON).
  # @return [nil]
  describe 'gobd_export_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
