=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SimplebillyApi::GoodsReceiptApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GoodsReceiptApi' do
  before do
    # run before each test
    @api_instance = SimplebillyApi::GoodsReceiptApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GoodsReceiptApi' do
    it 'should create an instance of GoodsReceiptApi' do
      expect(@api_instance).to be_instance_of(SimplebillyApi::GoodsReceiptApi)
    end
  end

  # unit tests for create_goods_receipt
  # @param goods_receipt 
  # @param [Hash] opts the optional parameters
  # @return [GoodsReceipt]
  describe 'create_goods_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_goods_receipt
  # @param goods_receipt_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_goods_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_goods_receipt
  # @param goods_receipt_id 
  # @param [Hash] opts the optional parameters
  # @return [GoodsReceipt]
  describe 'get_goods_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_goods_receipts
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [String] :purchase_order_id 
  # @option opts [String] :supplier_name 
  # @option opts [String] :warehouse_id 
  # @return [Array<GoodsReceipt>]
  describe 'list_goods_receipts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
