=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SimplebillyApi::ImportRunnerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ImportRunnerApi' do
  before do
    # run before each test
    @api_instance = SimplebillyApi::ImportRunnerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImportRunnerApi' do
    it 'should create an instance of ImportRunnerApi' do
      expect(@api_instance).to be_instance_of(SimplebillyApi::ImportRunnerApi)
    end
  end

  # unit tests for get_import_status
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [ImportJobStatus]
  describe 'get_import_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for start_import
  # @param import_start_request 
  # @param [Hash] opts the optional parameters
  # @return [ImportStartResponse]
  describe 'start_import test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for test_import_connection
  # @param import_test_request 
  # @param [Hash] opts the optional parameters
  # @return [ImportTestResponse]
  describe 'test_import_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
