=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SimplebillyApi::MarketplaceApiApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MarketplaceApiApi' do
  before do
    # run before each test
    @api_instance = SimplebillyApi::MarketplaceApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplaceApiApi' do
    it 'should create an instance of MarketplaceApiApi' do
      expect(@api_instance).to be_instance_of(SimplebillyApi::MarketplaceApiApi)
    end
  end

  # unit tests for create_connection_api
  # Create a new connection (for API-key based platforms)
  # @param create_connection_request 
  # @param [Hash] opts the optional parameters
  # @return [MarketplaceConnection]
  describe 'create_connection_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_connection_api
  # Soft-delete a connection
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_connection_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_connection_api
  # Get a single connection
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [MarketplaceConnection]
  describe 'get_connection_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sync_direction_api
  # Get current sync direction configuration for a connection
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_sync_direction_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sync_logs_api
  # Get sync logs for a connection
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<SyncLog>]
  describe 'get_sync_logs_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_connections_api
  # List connections for the current tenant
  # @param [Hash] opts the optional parameters
  # @return [Array<MarketplaceConnection>]
  describe 'list_connections_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_platforms_api
  # List all supported platforms
  # @param [Hash] opts the optional parameters
  # @return [Array<PlatformInfo>]
  describe 'list_platforms_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for oauth_authorize_api
  # OAuth: initiate authorization flow
  # @param o_auth_authorize_request 
  # @param [Hash] opts the optional parameters
  # @return [OAuthAuthorizeResponse]
  describe 'oauth_authorize_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for oauth_callback_api
  # OAuth: handle callback after authorization
  # @param o_auth_callback_request 
  # @param [Hash] opts the optional parameters
  # @return [MarketplaceConnection]
  describe 'oauth_callback_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for trigger_sync_api
  # Trigger sync for a connection
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sync_type 
  # @option opts [String] :direction 
  # @return [SyncSummary]
  describe 'trigger_sync_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_connection_api
  # Update a connection
  # @param connection_id 
  # @param update_connection_request 
  # @param [Hash] opts the optional parameters
  # @return [MarketplaceConnection]
  describe 'update_connection_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_sync_direction_api
  # Update per-entity sync direction configuration for a connection
  # @param connection_id 
  # @param update_sync_direction_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_sync_direction_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for webhook_receiver_api
  # Webhook receiver
  # @param platform 
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'webhook_receiver_api test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
