=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SimplebillyApi::ServiceJobApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceJobApi' do
  before do
    # run before each test
    @api_instance = SimplebillyApi::ServiceJobApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceJobApi' do
    it 'should create an instance of ServiceJobApi' do
      expect(@api_instance).to be_instance_of(SimplebillyApi::ServiceJobApi)
    end
  end

  # unit tests for create_service_job
  # @param service_job_create 
  # @param [Hash] opts the optional parameters
  # @return [ServiceJob]
  describe 'create_service_job test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_service_job
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_service_job test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_service_job
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ServiceJob]
  describe 'get_service_job test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_service_jobs
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [String] :search 
  # @option opts [Boolean] :include_deleted Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set.
  # @return [Array<ServiceJob>]
  describe 'get_service_jobs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_service_job
  # @param id 
  # @param service_job_update 
  # @param [Hash] opts the optional parameters
  # @return [ServiceJob]
  describe 'update_service_job test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
