=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class AbsenceType
    VACATION = "vacation".freeze
    SICK = "sick".freeze
    SABBATICAL = "sabbatical".freeze
    PARENTAL = "parental".freeze
    OTHER = "other".freeze

    def self.all_vars
      @all_vars ||= [VACATION, SICK, SABBATICAL, PARENTAL, OTHER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AbsenceType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AbsenceType"
    end
  end
end
