=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class AiWorkerConfig < ApiModelBase
    attr_accessor :auto_reply

    attr_accessor :created_at

    attr_accessor :id

    attr_accessor :is_active

    attr_accessor :max_tool_calls

    attr_accessor :model

    attr_accessor :name

    attr_accessor :provider

    attr_accessor :system_prompt

    attr_accessor :tenant_id

    attr_accessor :trigger_on

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'auto_reply' => :'auto_reply',
        :'created_at' => :'created_at',
        :'id' => :'id',
        :'is_active' => :'is_active',
        :'max_tool_calls' => :'max_tool_calls',
        :'model' => :'model',
        :'name' => :'name',
        :'provider' => :'provider',
        :'system_prompt' => :'system_prompt',
        :'tenant_id' => :'tenant_id',
        :'trigger_on' => :'trigger_on',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'auto_reply' => :'Boolean',
        :'created_at' => :'Time',
        :'id' => :'String',
        :'is_active' => :'Boolean',
        :'max_tool_calls' => :'Integer',
        :'model' => :'String',
        :'name' => :'String',
        :'provider' => :'String',
        :'system_prompt' => :'String',
        :'tenant_id' => :'String',
        :'trigger_on' => :'Array<String>',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'updated_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::AiWorkerConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::AiWorkerConfig`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'auto_reply')
        self.auto_reply = attributes[:'auto_reply']
      else
        self.auto_reply = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'is_active')
        self.is_active = attributes[:'is_active']
      else
        self.is_active = nil
      end

      if attributes.key?(:'max_tool_calls')
        self.max_tool_calls = attributes[:'max_tool_calls']
      else
        self.max_tool_calls = nil
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      else
        self.model = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'provider')
        self.provider = attributes[:'provider']
      else
        self.provider = nil
      end

      if attributes.key?(:'system_prompt')
        self.system_prompt = attributes[:'system_prompt']
      else
        self.system_prompt = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'trigger_on')
        if (value = attributes[:'trigger_on']).is_a?(Array)
          self.trigger_on = value
        end
      else
        self.trigger_on = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @auto_reply.nil?
        invalid_properties.push('invalid value for "auto_reply", auto_reply cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @is_active.nil?
        invalid_properties.push('invalid value for "is_active", is_active cannot be nil.')
      end

      if @max_tool_calls.nil?
        invalid_properties.push('invalid value for "max_tool_calls", max_tool_calls cannot be nil.')
      end

      if @model.nil?
        invalid_properties.push('invalid value for "model", model cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @provider.nil?
        invalid_properties.push('invalid value for "provider", provider cannot be nil.')
      end

      if @system_prompt.nil?
        invalid_properties.push('invalid value for "system_prompt", system_prompt cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @trigger_on.nil?
        invalid_properties.push('invalid value for "trigger_on", trigger_on cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @auto_reply.nil?
      return false if @created_at.nil?
      return false if @id.nil?
      return false if @is_active.nil?
      return false if @max_tool_calls.nil?
      return false if @model.nil?
      return false if @name.nil?
      return false if @provider.nil?
      return false if @system_prompt.nil?
      return false if @tenant_id.nil?
      return false if @trigger_on.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] auto_reply Value to be assigned
    def auto_reply=(auto_reply)
      if auto_reply.nil?
        fail ArgumentError, 'auto_reply cannot be nil'
      end

      @auto_reply = auto_reply
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] is_active Value to be assigned
    def is_active=(is_active)
      if is_active.nil?
        fail ArgumentError, 'is_active cannot be nil'
      end

      @is_active = is_active
    end

    # Custom attribute writer method with validation
    # @param [Object] max_tool_calls Value to be assigned
    def max_tool_calls=(max_tool_calls)
      if max_tool_calls.nil?
        fail ArgumentError, 'max_tool_calls cannot be nil'
      end

      @max_tool_calls = max_tool_calls
    end

    # Custom attribute writer method with validation
    # @param [Object] model Value to be assigned
    def model=(model)
      if model.nil?
        fail ArgumentError, 'model cannot be nil'
      end

      @model = model
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] provider Value to be assigned
    def provider=(provider)
      if provider.nil?
        fail ArgumentError, 'provider cannot be nil'
      end

      @provider = provider
    end

    # Custom attribute writer method with validation
    # @param [Object] system_prompt Value to be assigned
    def system_prompt=(system_prompt)
      if system_prompt.nil?
        fail ArgumentError, 'system_prompt cannot be nil'
      end

      @system_prompt = system_prompt
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] trigger_on Value to be assigned
    def trigger_on=(trigger_on)
      if trigger_on.nil?
        fail ArgumentError, 'trigger_on cannot be nil'
      end

      @trigger_on = trigger_on
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          auto_reply == o.auto_reply &&
          created_at == o.created_at &&
          id == o.id &&
          is_active == o.is_active &&
          max_tool_calls == o.max_tool_calls &&
          model == o.model &&
          name == o.name &&
          provider == o.provider &&
          system_prompt == o.system_prompt &&
          tenant_id == o.tenant_id &&
          trigger_on == o.trigger_on &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [auto_reply, created_at, id, is_active, max_tool_calls, model, name, provider, system_prompt, tenant_id, trigger_on, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
