=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class Contact < ApiModelBase
    attr_accessor :account_holder

    attr_accessor :acquisition_cost

    attr_accessor :address_supplement

    attr_accessor :attention

    attr_accessor :bank_name

    attr_accessor :bic

    attr_accessor :buyer_reference

    attr_accessor :category

    attr_accessor :certificate_authority

    attr_accessor :certificate_number

    attr_accessor :certificate_paragraph

    attr_accessor :certificate_valid_until

    attr_accessor :city

    attr_accessor :company_name

    attr_accessor :contact_id

    attr_accessor :contact_persons

    attr_accessor :contact_type

    attr_accessor :country

    attr_accessor :created_at

    attr_accessor :credit_limit

    attr_accessor :creditor_account_skr03

    attr_accessor :creditor_account_skr04

    attr_accessor :currency

    attr_accessor :customer_number

    attr_accessor :debitor_account_skr03

    attr_accessor :debitor_account_skr04

    attr_accessor :default_debitor_number

    attr_accessor :delivery_block

    attr_accessor :department

    attr_accessor :discount_days

    attr_accessor :discount_percentage

    attr_accessor :donation_receipt_eligible

    attr_accessor :email

    attr_accessor :external_id

    attr_accessor :fax

    attr_accessor :iban

    attr_accessor :industry

    attr_accessor :is_active

    attr_accessor :is_member

    attr_accessor :is_nonprofit

    attr_accessor :last_contact_date

    attr_accessor :last_purchase_date

    attr_accessor :leitweg_id

    attr_accessor :lifetime_value

    attr_accessor :mandate_date

    attr_accessor :mandate_reference

    attr_accessor :marketing_consent

    attr_accessor :marketing_consent_at

    attr_accessor :marketing_consent_source

    attr_accessor :mobile

    attr_accessor :name

    attr_accessor :next_contact_date

    attr_accessor :notes

    attr_accessor :opening_balance

    attr_accessor :opening_balance_date

    attr_accessor :order_reference

    attr_accessor :payment_block

    attr_accessor :payment_grace_period_days

    attr_accessor :payment_methods

    attr_accessor :payment_terms

    attr_accessor :phone

    attr_accessor :rating

    attr_accessor :sales_representative

    attr_accessor :social_media

    attr_accessor :source

    attr_accessor :state

    attr_accessor :street

    attr_accessor :street_number

    attr_accessor :supplier_number

    attr_accessor :tags

    attr_accessor :tax_country

    attr_accessor :tax_number

    attr_accessor :tax_office

    attr_accessor :total_invoices

    attr_accessor :total_revenue

    attr_accessor :updated_at

    attr_accessor :vat_id

    attr_accessor :vat_id_validated

    attr_accessor :vat_id_validation_date

    attr_accessor :website

    attr_accessor :zip

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_holder' => :'account_holder',
        :'acquisition_cost' => :'acquisition_cost',
        :'address_supplement' => :'address_supplement',
        :'attention' => :'attention',
        :'bank_name' => :'bank_name',
        :'bic' => :'bic',
        :'buyer_reference' => :'buyer_reference',
        :'category' => :'category',
        :'certificate_authority' => :'certificate_authority',
        :'certificate_number' => :'certificate_number',
        :'certificate_paragraph' => :'certificate_paragraph',
        :'certificate_valid_until' => :'certificate_valid_until',
        :'city' => :'city',
        :'company_name' => :'company_name',
        :'contact_id' => :'contact_id',
        :'contact_persons' => :'contact_persons',
        :'contact_type' => :'contact_type',
        :'country' => :'country',
        :'created_at' => :'created_at',
        :'credit_limit' => :'credit_limit',
        :'creditor_account_skr03' => :'creditor_account_skr03',
        :'creditor_account_skr04' => :'creditor_account_skr04',
        :'currency' => :'currency',
        :'customer_number' => :'customer_number',
        :'debitor_account_skr03' => :'debitor_account_skr03',
        :'debitor_account_skr04' => :'debitor_account_skr04',
        :'default_debitor_number' => :'default_debitor_number',
        :'delivery_block' => :'delivery_block',
        :'department' => :'department',
        :'discount_days' => :'discount_days',
        :'discount_percentage' => :'discount_percentage',
        :'donation_receipt_eligible' => :'donation_receipt_eligible',
        :'email' => :'email',
        :'external_id' => :'external_id',
        :'fax' => :'fax',
        :'iban' => :'iban',
        :'industry' => :'industry',
        :'is_active' => :'is_active',
        :'is_member' => :'is_member',
        :'is_nonprofit' => :'is_nonprofit',
        :'last_contact_date' => :'last_contact_date',
        :'last_purchase_date' => :'last_purchase_date',
        :'leitweg_id' => :'leitweg_id',
        :'lifetime_value' => :'lifetime_value',
        :'mandate_date' => :'mandate_date',
        :'mandate_reference' => :'mandate_reference',
        :'marketing_consent' => :'marketing_consent',
        :'marketing_consent_at' => :'marketing_consent_at',
        :'marketing_consent_source' => :'marketing_consent_source',
        :'mobile' => :'mobile',
        :'name' => :'name',
        :'next_contact_date' => :'next_contact_date',
        :'notes' => :'notes',
        :'opening_balance' => :'opening_balance',
        :'opening_balance_date' => :'opening_balance_date',
        :'order_reference' => :'order_reference',
        :'payment_block' => :'payment_block',
        :'payment_grace_period_days' => :'payment_grace_period_days',
        :'payment_methods' => :'payment_methods',
        :'payment_terms' => :'payment_terms',
        :'phone' => :'phone',
        :'rating' => :'rating',
        :'sales_representative' => :'sales_representative',
        :'social_media' => :'social_media',
        :'source' => :'source',
        :'state' => :'state',
        :'street' => :'street',
        :'street_number' => :'street_number',
        :'supplier_number' => :'supplier_number',
        :'tags' => :'tags',
        :'tax_country' => :'tax_country',
        :'tax_number' => :'tax_number',
        :'tax_office' => :'tax_office',
        :'total_invoices' => :'total_invoices',
        :'total_revenue' => :'total_revenue',
        :'updated_at' => :'updated_at',
        :'vat_id' => :'vat_id',
        :'vat_id_validated' => :'vat_id_validated',
        :'vat_id_validation_date' => :'vat_id_validation_date',
        :'website' => :'website',
        :'zip' => :'zip'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_holder' => :'String',
        :'acquisition_cost' => :'String',
        :'address_supplement' => :'String',
        :'attention' => :'String',
        :'bank_name' => :'String',
        :'bic' => :'String',
        :'buyer_reference' => :'String',
        :'category' => :'String',
        :'certificate_authority' => :'String',
        :'certificate_number' => :'String',
        :'certificate_paragraph' => :'String',
        :'certificate_valid_until' => :'String',
        :'city' => :'String',
        :'company_name' => :'String',
        :'contact_id' => :'String',
        :'contact_persons' => :'Object',
        :'contact_type' => :'String',
        :'country' => :'String',
        :'created_at' => :'String',
        :'credit_limit' => :'String',
        :'creditor_account_skr03' => :'String',
        :'creditor_account_skr04' => :'String',
        :'currency' => :'String',
        :'customer_number' => :'String',
        :'debitor_account_skr03' => :'String',
        :'debitor_account_skr04' => :'String',
        :'default_debitor_number' => :'String',
        :'delivery_block' => :'Boolean',
        :'department' => :'String',
        :'discount_days' => :'Integer',
        :'discount_percentage' => :'String',
        :'donation_receipt_eligible' => :'Boolean',
        :'email' => :'String',
        :'external_id' => :'String',
        :'fax' => :'String',
        :'iban' => :'String',
        :'industry' => :'String',
        :'is_active' => :'Boolean',
        :'is_member' => :'Boolean',
        :'is_nonprofit' => :'Boolean',
        :'last_contact_date' => :'String',
        :'last_purchase_date' => :'String',
        :'leitweg_id' => :'String',
        :'lifetime_value' => :'String',
        :'mandate_date' => :'String',
        :'mandate_reference' => :'String',
        :'marketing_consent' => :'Boolean',
        :'marketing_consent_at' => :'String',
        :'marketing_consent_source' => :'String',
        :'mobile' => :'String',
        :'name' => :'String',
        :'next_contact_date' => :'String',
        :'notes' => :'String',
        :'opening_balance' => :'String',
        :'opening_balance_date' => :'String',
        :'order_reference' => :'String',
        :'payment_block' => :'Boolean',
        :'payment_grace_period_days' => :'Integer',
        :'payment_methods' => :'Array<String>',
        :'payment_terms' => :'String',
        :'phone' => :'String',
        :'rating' => :'Integer',
        :'sales_representative' => :'String',
        :'social_media' => :'Object',
        :'source' => :'String',
        :'state' => :'String',
        :'street' => :'String',
        :'street_number' => :'String',
        :'supplier_number' => :'String',
        :'tags' => :'Array<String>',
        :'tax_country' => :'String',
        :'tax_number' => :'String',
        :'tax_office' => :'String',
        :'total_invoices' => :'Integer',
        :'total_revenue' => :'String',
        :'updated_at' => :'String',
        :'vat_id' => :'String',
        :'vat_id_validated' => :'Boolean',
        :'vat_id_validation_date' => :'String',
        :'website' => :'String',
        :'zip' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'account_holder',
        :'acquisition_cost',
        :'address_supplement',
        :'attention',
        :'bank_name',
        :'bic',
        :'buyer_reference',
        :'category',
        :'certificate_authority',
        :'certificate_number',
        :'certificate_paragraph',
        :'certificate_valid_until',
        :'city',
        :'company_name',
        :'contact_persons',
        :'country',
        :'credit_limit',
        :'creditor_account_skr03',
        :'creditor_account_skr04',
        :'currency',
        :'customer_number',
        :'debitor_account_skr03',
        :'debitor_account_skr04',
        :'default_debitor_number',
        :'delivery_block',
        :'department',
        :'discount_days',
        :'discount_percentage',
        :'donation_receipt_eligible',
        :'email',
        :'external_id',
        :'fax',
        :'iban',
        :'industry',
        :'is_active',
        :'is_member',
        :'is_nonprofit',
        :'last_contact_date',
        :'last_purchase_date',
        :'leitweg_id',
        :'lifetime_value',
        :'mandate_date',
        :'mandate_reference',
        :'marketing_consent',
        :'marketing_consent_at',
        :'marketing_consent_source',
        :'mobile',
        :'next_contact_date',
        :'notes',
        :'opening_balance',
        :'opening_balance_date',
        :'order_reference',
        :'payment_block',
        :'payment_grace_period_days',
        :'payment_methods',
        :'payment_terms',
        :'phone',
        :'rating',
        :'sales_representative',
        :'social_media',
        :'source',
        :'state',
        :'street',
        :'street_number',
        :'supplier_number',
        :'tags',
        :'tax_country',
        :'tax_number',
        :'tax_office',
        :'total_invoices',
        :'total_revenue',
        :'updated_at',
        :'vat_id',
        :'vat_id_validated',
        :'vat_id_validation_date',
        :'website',
        :'zip'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::Contact` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::Contact`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_holder')
        self.account_holder = attributes[:'account_holder']
      end

      if attributes.key?(:'acquisition_cost')
        self.acquisition_cost = attributes[:'acquisition_cost']
      end

      if attributes.key?(:'address_supplement')
        self.address_supplement = attributes[:'address_supplement']
      end

      if attributes.key?(:'attention')
        self.attention = attributes[:'attention']
      end

      if attributes.key?(:'bank_name')
        self.bank_name = attributes[:'bank_name']
      end

      if attributes.key?(:'bic')
        self.bic = attributes[:'bic']
      end

      if attributes.key?(:'buyer_reference')
        self.buyer_reference = attributes[:'buyer_reference']
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'certificate_authority')
        self.certificate_authority = attributes[:'certificate_authority']
      end

      if attributes.key?(:'certificate_number')
        self.certificate_number = attributes[:'certificate_number']
      end

      if attributes.key?(:'certificate_paragraph')
        self.certificate_paragraph = attributes[:'certificate_paragraph']
      end

      if attributes.key?(:'certificate_valid_until')
        self.certificate_valid_until = attributes[:'certificate_valid_until']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'company_name')
        self.company_name = attributes[:'company_name']
      end

      if attributes.key?(:'contact_id')
        self.contact_id = attributes[:'contact_id']
      else
        self.contact_id = nil
      end

      if attributes.key?(:'contact_persons')
        self.contact_persons = attributes[:'contact_persons']
      else
        self.contact_persons = nil
      end

      if attributes.key?(:'contact_type')
        self.contact_type = attributes[:'contact_type']
      else
        self.contact_type = nil
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'credit_limit')
        self.credit_limit = attributes[:'credit_limit']
      end

      if attributes.key?(:'creditor_account_skr03')
        self.creditor_account_skr03 = attributes[:'creditor_account_skr03']
      end

      if attributes.key?(:'creditor_account_skr04')
        self.creditor_account_skr04 = attributes[:'creditor_account_skr04']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'customer_number')
        self.customer_number = attributes[:'customer_number']
      end

      if attributes.key?(:'debitor_account_skr03')
        self.debitor_account_skr03 = attributes[:'debitor_account_skr03']
      end

      if attributes.key?(:'debitor_account_skr04')
        self.debitor_account_skr04 = attributes[:'debitor_account_skr04']
      end

      if attributes.key?(:'default_debitor_number')
        self.default_debitor_number = attributes[:'default_debitor_number']
      end

      if attributes.key?(:'delivery_block')
        self.delivery_block = attributes[:'delivery_block']
      end

      if attributes.key?(:'department')
        self.department = attributes[:'department']
      end

      if attributes.key?(:'discount_days')
        self.discount_days = attributes[:'discount_days']
      end

      if attributes.key?(:'discount_percentage')
        self.discount_percentage = attributes[:'discount_percentage']
      end

      if attributes.key?(:'donation_receipt_eligible')
        self.donation_receipt_eligible = attributes[:'donation_receipt_eligible']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'fax')
        self.fax = attributes[:'fax']
      end

      if attributes.key?(:'iban')
        self.iban = attributes[:'iban']
      end

      if attributes.key?(:'industry')
        self.industry = attributes[:'industry']
      end

      if attributes.key?(:'is_active')
        self.is_active = attributes[:'is_active']
      end

      if attributes.key?(:'is_member')
        self.is_member = attributes[:'is_member']
      end

      if attributes.key?(:'is_nonprofit')
        self.is_nonprofit = attributes[:'is_nonprofit']
      end

      if attributes.key?(:'last_contact_date')
        self.last_contact_date = attributes[:'last_contact_date']
      end

      if attributes.key?(:'last_purchase_date')
        self.last_purchase_date = attributes[:'last_purchase_date']
      end

      if attributes.key?(:'leitweg_id')
        self.leitweg_id = attributes[:'leitweg_id']
      end

      if attributes.key?(:'lifetime_value')
        self.lifetime_value = attributes[:'lifetime_value']
      end

      if attributes.key?(:'mandate_date')
        self.mandate_date = attributes[:'mandate_date']
      end

      if attributes.key?(:'mandate_reference')
        self.mandate_reference = attributes[:'mandate_reference']
      end

      if attributes.key?(:'marketing_consent')
        self.marketing_consent = attributes[:'marketing_consent']
      end

      if attributes.key?(:'marketing_consent_at')
        self.marketing_consent_at = attributes[:'marketing_consent_at']
      end

      if attributes.key?(:'marketing_consent_source')
        self.marketing_consent_source = attributes[:'marketing_consent_source']
      end

      if attributes.key?(:'mobile')
        self.mobile = attributes[:'mobile']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'next_contact_date')
        self.next_contact_date = attributes[:'next_contact_date']
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end

      if attributes.key?(:'opening_balance')
        self.opening_balance = attributes[:'opening_balance']
      end

      if attributes.key?(:'opening_balance_date')
        self.opening_balance_date = attributes[:'opening_balance_date']
      end

      if attributes.key?(:'order_reference')
        self.order_reference = attributes[:'order_reference']
      end

      if attributes.key?(:'payment_block')
        self.payment_block = attributes[:'payment_block']
      end

      if attributes.key?(:'payment_grace_period_days')
        self.payment_grace_period_days = attributes[:'payment_grace_period_days']
      end

      if attributes.key?(:'payment_methods')
        if (value = attributes[:'payment_methods']).is_a?(Array)
          self.payment_methods = value
        end
      end

      if attributes.key?(:'payment_terms')
        self.payment_terms = attributes[:'payment_terms']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'rating')
        self.rating = attributes[:'rating']
      end

      if attributes.key?(:'sales_representative')
        self.sales_representative = attributes[:'sales_representative']
      end

      if attributes.key?(:'social_media')
        self.social_media = attributes[:'social_media']
      else
        self.social_media = nil
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'street')
        self.street = attributes[:'street']
      end

      if attributes.key?(:'street_number')
        self.street_number = attributes[:'street_number']
      end

      if attributes.key?(:'supplier_number')
        self.supplier_number = attributes[:'supplier_number']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'tax_country')
        self.tax_country = attributes[:'tax_country']
      end

      if attributes.key?(:'tax_number')
        self.tax_number = attributes[:'tax_number']
      end

      if attributes.key?(:'tax_office')
        self.tax_office = attributes[:'tax_office']
      end

      if attributes.key?(:'total_invoices')
        self.total_invoices = attributes[:'total_invoices']
      end

      if attributes.key?(:'total_revenue')
        self.total_revenue = attributes[:'total_revenue']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'vat_id')
        self.vat_id = attributes[:'vat_id']
      end

      if attributes.key?(:'vat_id_validated')
        self.vat_id_validated = attributes[:'vat_id_validated']
      end

      if attributes.key?(:'vat_id_validation_date')
        self.vat_id_validation_date = attributes[:'vat_id_validation_date']
      end

      if attributes.key?(:'website')
        self.website = attributes[:'website']
      end

      if attributes.key?(:'zip')
        self.zip = attributes[:'zip']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @contact_id.nil?
        invalid_properties.push('invalid value for "contact_id", contact_id cannot be nil.')
      end

      if @contact_type.nil?
        invalid_properties.push('invalid value for "contact_type", contact_type cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @contact_id.nil?
      return false if @contact_type.nil?
      return false if @created_at.nil?
      return false if @name.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] contact_id Value to be assigned
    def contact_id=(contact_id)
      if contact_id.nil?
        fail ArgumentError, 'contact_id cannot be nil'
      end

      @contact_id = contact_id
    end

    # Custom attribute writer method with validation
    # @param [Object] contact_type Value to be assigned
    def contact_type=(contact_type)
      if contact_type.nil?
        fail ArgumentError, 'contact_type cannot be nil'
      end

      @contact_type = contact_type
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_holder == o.account_holder &&
          acquisition_cost == o.acquisition_cost &&
          address_supplement == o.address_supplement &&
          attention == o.attention &&
          bank_name == o.bank_name &&
          bic == o.bic &&
          buyer_reference == o.buyer_reference &&
          category == o.category &&
          certificate_authority == o.certificate_authority &&
          certificate_number == o.certificate_number &&
          certificate_paragraph == o.certificate_paragraph &&
          certificate_valid_until == o.certificate_valid_until &&
          city == o.city &&
          company_name == o.company_name &&
          contact_id == o.contact_id &&
          contact_persons == o.contact_persons &&
          contact_type == o.contact_type &&
          country == o.country &&
          created_at == o.created_at &&
          credit_limit == o.credit_limit &&
          creditor_account_skr03 == o.creditor_account_skr03 &&
          creditor_account_skr04 == o.creditor_account_skr04 &&
          currency == o.currency &&
          customer_number == o.customer_number &&
          debitor_account_skr03 == o.debitor_account_skr03 &&
          debitor_account_skr04 == o.debitor_account_skr04 &&
          default_debitor_number == o.default_debitor_number &&
          delivery_block == o.delivery_block &&
          department == o.department &&
          discount_days == o.discount_days &&
          discount_percentage == o.discount_percentage &&
          donation_receipt_eligible == o.donation_receipt_eligible &&
          email == o.email &&
          external_id == o.external_id &&
          fax == o.fax &&
          iban == o.iban &&
          industry == o.industry &&
          is_active == o.is_active &&
          is_member == o.is_member &&
          is_nonprofit == o.is_nonprofit &&
          last_contact_date == o.last_contact_date &&
          last_purchase_date == o.last_purchase_date &&
          leitweg_id == o.leitweg_id &&
          lifetime_value == o.lifetime_value &&
          mandate_date == o.mandate_date &&
          mandate_reference == o.mandate_reference &&
          marketing_consent == o.marketing_consent &&
          marketing_consent_at == o.marketing_consent_at &&
          marketing_consent_source == o.marketing_consent_source &&
          mobile == o.mobile &&
          name == o.name &&
          next_contact_date == o.next_contact_date &&
          notes == o.notes &&
          opening_balance == o.opening_balance &&
          opening_balance_date == o.opening_balance_date &&
          order_reference == o.order_reference &&
          payment_block == o.payment_block &&
          payment_grace_period_days == o.payment_grace_period_days &&
          payment_methods == o.payment_methods &&
          payment_terms == o.payment_terms &&
          phone == o.phone &&
          rating == o.rating &&
          sales_representative == o.sales_representative &&
          social_media == o.social_media &&
          source == o.source &&
          state == o.state &&
          street == o.street &&
          street_number == o.street_number &&
          supplier_number == o.supplier_number &&
          tags == o.tags &&
          tax_country == o.tax_country &&
          tax_number == o.tax_number &&
          tax_office == o.tax_office &&
          total_invoices == o.total_invoices &&
          total_revenue == o.total_revenue &&
          updated_at == o.updated_at &&
          vat_id == o.vat_id &&
          vat_id_validated == o.vat_id_validated &&
          vat_id_validation_date == o.vat_id_validation_date &&
          website == o.website &&
          zip == o.zip
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_holder, acquisition_cost, address_supplement, attention, bank_name, bic, buyer_reference, category, certificate_authority, certificate_number, certificate_paragraph, certificate_valid_until, city, company_name, contact_id, contact_persons, contact_type, country, created_at, credit_limit, creditor_account_skr03, creditor_account_skr04, currency, customer_number, debitor_account_skr03, debitor_account_skr04, default_debitor_number, delivery_block, department, discount_days, discount_percentage, donation_receipt_eligible, email, external_id, fax, iban, industry, is_active, is_member, is_nonprofit, last_contact_date, last_purchase_date, leitweg_id, lifetime_value, mandate_date, mandate_reference, marketing_consent, marketing_consent_at, marketing_consent_source, mobile, name, next_contact_date, notes, opening_balance, opening_balance_date, order_reference, payment_block, payment_grace_period_days, payment_methods, payment_terms, phone, rating, sales_representative, social_media, source, state, street, street_number, supplier_number, tags, tax_country, tax_number, tax_office, total_invoices, total_revenue, updated_at, vat_id, vat_id_validated, vat_id_validation_date, website, zip].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
