=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class GewerbesteuerErgebnis < ApiModelBase
    attr_accessor :freibetrag

    attr_accessor :gesamtbelastung

    attr_accessor :gewerbeertrag

    attr_accessor :hebesatz

    attr_accessor :jahr

    attr_accessor :koerperschaftsteuer

    attr_accessor :land

    attr_accessor :messbetrag

    attr_accessor :steuer

    attr_accessor :steuer_art

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'freibetrag' => :'freibetrag',
        :'gesamtbelastung' => :'gesamtbelastung',
        :'gewerbeertrag' => :'gewerbeertrag',
        :'hebesatz' => :'hebesatz',
        :'jahr' => :'jahr',
        :'koerperschaftsteuer' => :'koerperschaftsteuer',
        :'land' => :'land',
        :'messbetrag' => :'messbetrag',
        :'steuer' => :'steuer',
        :'steuer_art' => :'steuer_art'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'freibetrag' => :'String',
        :'gesamtbelastung' => :'String',
        :'gewerbeertrag' => :'String',
        :'hebesatz' => :'String',
        :'jahr' => :'Integer',
        :'koerperschaftsteuer' => :'String',
        :'land' => :'String',
        :'messbetrag' => :'String',
        :'steuer' => :'String',
        :'steuer_art' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::GewerbesteuerErgebnis` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::GewerbesteuerErgebnis`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'freibetrag')
        self.freibetrag = attributes[:'freibetrag']
      else
        self.freibetrag = nil
      end

      if attributes.key?(:'gesamtbelastung')
        self.gesamtbelastung = attributes[:'gesamtbelastung']
      else
        self.gesamtbelastung = nil
      end

      if attributes.key?(:'gewerbeertrag')
        self.gewerbeertrag = attributes[:'gewerbeertrag']
      else
        self.gewerbeertrag = nil
      end

      if attributes.key?(:'hebesatz')
        self.hebesatz = attributes[:'hebesatz']
      else
        self.hebesatz = nil
      end

      if attributes.key?(:'jahr')
        self.jahr = attributes[:'jahr']
      else
        self.jahr = nil
      end

      if attributes.key?(:'koerperschaftsteuer')
        self.koerperschaftsteuer = attributes[:'koerperschaftsteuer']
      else
        self.koerperschaftsteuer = nil
      end

      if attributes.key?(:'land')
        self.land = attributes[:'land']
      else
        self.land = nil
      end

      if attributes.key?(:'messbetrag')
        self.messbetrag = attributes[:'messbetrag']
      else
        self.messbetrag = nil
      end

      if attributes.key?(:'steuer')
        self.steuer = attributes[:'steuer']
      else
        self.steuer = nil
      end

      if attributes.key?(:'steuer_art')
        self.steuer_art = attributes[:'steuer_art']
      else
        self.steuer_art = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @freibetrag.nil?
        invalid_properties.push('invalid value for "freibetrag", freibetrag cannot be nil.')
      end

      if @gesamtbelastung.nil?
        invalid_properties.push('invalid value for "gesamtbelastung", gesamtbelastung cannot be nil.')
      end

      if @gewerbeertrag.nil?
        invalid_properties.push('invalid value for "gewerbeertrag", gewerbeertrag cannot be nil.')
      end

      if @hebesatz.nil?
        invalid_properties.push('invalid value for "hebesatz", hebesatz cannot be nil.')
      end

      if @jahr.nil?
        invalid_properties.push('invalid value for "jahr", jahr cannot be nil.')
      end

      if @koerperschaftsteuer.nil?
        invalid_properties.push('invalid value for "koerperschaftsteuer", koerperschaftsteuer cannot be nil.')
      end

      if @land.nil?
        invalid_properties.push('invalid value for "land", land cannot be nil.')
      end

      if @messbetrag.nil?
        invalid_properties.push('invalid value for "messbetrag", messbetrag cannot be nil.')
      end

      if @steuer.nil?
        invalid_properties.push('invalid value for "steuer", steuer cannot be nil.')
      end

      if @steuer_art.nil?
        invalid_properties.push('invalid value for "steuer_art", steuer_art cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @freibetrag.nil?
      return false if @gesamtbelastung.nil?
      return false if @gewerbeertrag.nil?
      return false if @hebesatz.nil?
      return false if @jahr.nil?
      return false if @koerperschaftsteuer.nil?
      return false if @land.nil?
      return false if @messbetrag.nil?
      return false if @steuer.nil?
      return false if @steuer_art.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] freibetrag Value to be assigned
    def freibetrag=(freibetrag)
      if freibetrag.nil?
        fail ArgumentError, 'freibetrag cannot be nil'
      end

      @freibetrag = freibetrag
    end

    # Custom attribute writer method with validation
    # @param [Object] gesamtbelastung Value to be assigned
    def gesamtbelastung=(gesamtbelastung)
      if gesamtbelastung.nil?
        fail ArgumentError, 'gesamtbelastung cannot be nil'
      end

      @gesamtbelastung = gesamtbelastung
    end

    # Custom attribute writer method with validation
    # @param [Object] gewerbeertrag Value to be assigned
    def gewerbeertrag=(gewerbeertrag)
      if gewerbeertrag.nil?
        fail ArgumentError, 'gewerbeertrag cannot be nil'
      end

      @gewerbeertrag = gewerbeertrag
    end

    # Custom attribute writer method with validation
    # @param [Object] hebesatz Value to be assigned
    def hebesatz=(hebesatz)
      if hebesatz.nil?
        fail ArgumentError, 'hebesatz cannot be nil'
      end

      @hebesatz = hebesatz
    end

    # Custom attribute writer method with validation
    # @param [Object] jahr Value to be assigned
    def jahr=(jahr)
      if jahr.nil?
        fail ArgumentError, 'jahr cannot be nil'
      end

      @jahr = jahr
    end

    # Custom attribute writer method with validation
    # @param [Object] koerperschaftsteuer Value to be assigned
    def koerperschaftsteuer=(koerperschaftsteuer)
      if koerperschaftsteuer.nil?
        fail ArgumentError, 'koerperschaftsteuer cannot be nil'
      end

      @koerperschaftsteuer = koerperschaftsteuer
    end

    # Custom attribute writer method with validation
    # @param [Object] land Value to be assigned
    def land=(land)
      if land.nil?
        fail ArgumentError, 'land cannot be nil'
      end

      @land = land
    end

    # Custom attribute writer method with validation
    # @param [Object] messbetrag Value to be assigned
    def messbetrag=(messbetrag)
      if messbetrag.nil?
        fail ArgumentError, 'messbetrag cannot be nil'
      end

      @messbetrag = messbetrag
    end

    # Custom attribute writer method with validation
    # @param [Object] steuer Value to be assigned
    def steuer=(steuer)
      if steuer.nil?
        fail ArgumentError, 'steuer cannot be nil'
      end

      @steuer = steuer
    end

    # Custom attribute writer method with validation
    # @param [Object] steuer_art Value to be assigned
    def steuer_art=(steuer_art)
      if steuer_art.nil?
        fail ArgumentError, 'steuer_art cannot be nil'
      end

      @steuer_art = steuer_art
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          freibetrag == o.freibetrag &&
          gesamtbelastung == o.gesamtbelastung &&
          gewerbeertrag == o.gewerbeertrag &&
          hebesatz == o.hebesatz &&
          jahr == o.jahr &&
          koerperschaftsteuer == o.koerperschaftsteuer &&
          land == o.land &&
          messbetrag == o.messbetrag &&
          steuer == o.steuer &&
          steuer_art == o.steuer_art
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [freibetrag, gesamtbelastung, gewerbeertrag, hebesatz, jahr, koerperschaftsteuer, land, messbetrag, steuer, steuer_art].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
