=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class HebesatzLookup < ApiModelBase
    attr_accessor :bundesland

    attr_accessor :country_code

    attr_accessor :gemeinde_name

    attr_accessor :gemeindeschluessel

    attr_accessor :hebesatz_gewerbesteuer

    attr_accessor :hebesatz_grundsteuer_b

    attr_accessor :jahr

    attr_accessor :landkreis

    attr_accessor :valid_from

    attr_accessor :valid_to

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bundesland' => :'bundesland',
        :'country_code' => :'country_code',
        :'gemeinde_name' => :'gemeinde_name',
        :'gemeindeschluessel' => :'gemeindeschluessel',
        :'hebesatz_gewerbesteuer' => :'hebesatz_gewerbesteuer',
        :'hebesatz_grundsteuer_b' => :'hebesatz_grundsteuer_b',
        :'jahr' => :'jahr',
        :'landkreis' => :'landkreis',
        :'valid_from' => :'valid_from',
        :'valid_to' => :'valid_to'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'bundesland' => :'String',
        :'country_code' => :'String',
        :'gemeinde_name' => :'String',
        :'gemeindeschluessel' => :'String',
        :'hebesatz_gewerbesteuer' => :'Float',
        :'hebesatz_grundsteuer_b' => :'Float',
        :'jahr' => :'Integer',
        :'landkreis' => :'String',
        :'valid_from' => :'String',
        :'valid_to' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'hebesatz_grundsteuer_b',
        :'landkreis',
        :'valid_to'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::HebesatzLookup` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::HebesatzLookup`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'bundesland')
        self.bundesland = attributes[:'bundesland']
      else
        self.bundesland = nil
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      else
        self.country_code = nil
      end

      if attributes.key?(:'gemeinde_name')
        self.gemeinde_name = attributes[:'gemeinde_name']
      else
        self.gemeinde_name = nil
      end

      if attributes.key?(:'gemeindeschluessel')
        self.gemeindeschluessel = attributes[:'gemeindeschluessel']
      else
        self.gemeindeschluessel = nil
      end

      if attributes.key?(:'hebesatz_gewerbesteuer')
        self.hebesatz_gewerbesteuer = attributes[:'hebesatz_gewerbesteuer']
      else
        self.hebesatz_gewerbesteuer = nil
      end

      if attributes.key?(:'hebesatz_grundsteuer_b')
        self.hebesatz_grundsteuer_b = attributes[:'hebesatz_grundsteuer_b']
      end

      if attributes.key?(:'jahr')
        self.jahr = attributes[:'jahr']
      else
        self.jahr = nil
      end

      if attributes.key?(:'landkreis')
        self.landkreis = attributes[:'landkreis']
      end

      if attributes.key?(:'valid_from')
        self.valid_from = attributes[:'valid_from']
      else
        self.valid_from = nil
      end

      if attributes.key?(:'valid_to')
        self.valid_to = attributes[:'valid_to']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @bundesland.nil?
        invalid_properties.push('invalid value for "bundesland", bundesland cannot be nil.')
      end

      if @country_code.nil?
        invalid_properties.push('invalid value for "country_code", country_code cannot be nil.')
      end

      if @gemeinde_name.nil?
        invalid_properties.push('invalid value for "gemeinde_name", gemeinde_name cannot be nil.')
      end

      if @gemeindeschluessel.nil?
        invalid_properties.push('invalid value for "gemeindeschluessel", gemeindeschluessel cannot be nil.')
      end

      if @hebesatz_gewerbesteuer.nil?
        invalid_properties.push('invalid value for "hebesatz_gewerbesteuer", hebesatz_gewerbesteuer cannot be nil.')
      end

      if @jahr.nil?
        invalid_properties.push('invalid value for "jahr", jahr cannot be nil.')
      end

      if @valid_from.nil?
        invalid_properties.push('invalid value for "valid_from", valid_from cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @bundesland.nil?
      return false if @country_code.nil?
      return false if @gemeinde_name.nil?
      return false if @gemeindeschluessel.nil?
      return false if @hebesatz_gewerbesteuer.nil?
      return false if @jahr.nil?
      return false if @valid_from.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] bundesland Value to be assigned
    def bundesland=(bundesland)
      if bundesland.nil?
        fail ArgumentError, 'bundesland cannot be nil'
      end

      @bundesland = bundesland
    end

    # Custom attribute writer method with validation
    # @param [Object] country_code Value to be assigned
    def country_code=(country_code)
      if country_code.nil?
        fail ArgumentError, 'country_code cannot be nil'
      end

      @country_code = country_code
    end

    # Custom attribute writer method with validation
    # @param [Object] gemeinde_name Value to be assigned
    def gemeinde_name=(gemeinde_name)
      if gemeinde_name.nil?
        fail ArgumentError, 'gemeinde_name cannot be nil'
      end

      @gemeinde_name = gemeinde_name
    end

    # Custom attribute writer method with validation
    # @param [Object] gemeindeschluessel Value to be assigned
    def gemeindeschluessel=(gemeindeschluessel)
      if gemeindeschluessel.nil?
        fail ArgumentError, 'gemeindeschluessel cannot be nil'
      end

      @gemeindeschluessel = gemeindeschluessel
    end

    # Custom attribute writer method with validation
    # @param [Object] hebesatz_gewerbesteuer Value to be assigned
    def hebesatz_gewerbesteuer=(hebesatz_gewerbesteuer)
      if hebesatz_gewerbesteuer.nil?
        fail ArgumentError, 'hebesatz_gewerbesteuer cannot be nil'
      end

      @hebesatz_gewerbesteuer = hebesatz_gewerbesteuer
    end

    # Custom attribute writer method with validation
    # @param [Object] jahr Value to be assigned
    def jahr=(jahr)
      if jahr.nil?
        fail ArgumentError, 'jahr cannot be nil'
      end

      @jahr = jahr
    end

    # Custom attribute writer method with validation
    # @param [Object] valid_from Value to be assigned
    def valid_from=(valid_from)
      if valid_from.nil?
        fail ArgumentError, 'valid_from cannot be nil'
      end

      @valid_from = valid_from
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bundesland == o.bundesland &&
          country_code == o.country_code &&
          gemeinde_name == o.gemeinde_name &&
          gemeindeschluessel == o.gemeindeschluessel &&
          hebesatz_gewerbesteuer == o.hebesatz_gewerbesteuer &&
          hebesatz_grundsteuer_b == o.hebesatz_grundsteuer_b &&
          jahr == o.jahr &&
          landkreis == o.landkreis &&
          valid_from == o.valid_from &&
          valid_to == o.valid_to
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [bundesland, country_code, gemeinde_name, gemeindeschluessel, hebesatz_gewerbesteuer, hebesatz_grundsteuer_b, jahr, landkreis, valid_from, valid_to].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
