=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class Invoice < ApiModelBase
    attr_accessor :attachments

    attr_accessor :billing_period_end

    attr_accessor :billing_period_start

    attr_accessor :cancellation_date

    # References the invoice entity.
    attr_accessor :cancellation_invoice_id

    attr_accessor :cancellation_reason

    # References the contract entity.
    attr_accessor :contract_id

    attr_accessor :currency

    # References the customer entity.
    attr_accessor :customer_id

    attr_accessor :discount_amount

    attr_accessor :discount_days

    attr_accessor :discount_percentage

    attr_accessor :document_type

    attr_accessor :dunning_level

    attr_accessor :input_vat_amount

    attr_accessor :input_vat_deductible

    attr_accessor :input_vat_percentage

    attr_accessor :introduction_text

    attr_accessor :invoice_type

    attr_accessor :is_cancelled

    attr_accessor :is_draft

    attr_accessor :is_eu_acquisition

    attr_accessor :is_eu_delivery

    attr_accessor :is_intra_community_acquisition

    attr_accessor :is_reverse_charge

    attr_accessor :issue_date

    attr_accessor :ledger_account

    attr_accessor :line_items

    attr_accessor :margin25a

    attr_accessor :margin25a_gross

    attr_accessor :margin25a_purchase_price

    attr_accessor :notes

    attr_accessor :order_number

    attr_accessor :original_pdf_path

    attr_accessor :paid_amount

    attr_accessor :payment_due_date

    attr_accessor :payment_status

    attr_accessor :payment_terms_text

    # References the preceding sales voucher entity.
    attr_accessor :preceding_sales_voucher_id

    attr_accessor :preceding_sales_voucher_type

    attr_accessor :receipt_confirmation_available

    # References the invoice entity.
    attr_accessor :related_invoice_id

    attr_accessor :relationship_type

    attr_accessor :sender_snapshot

    attr_accessor :sent_at

    attr_accessor :service_period_end

    attr_accessor :service_period_start

    attr_accessor :status

    attr_accessor :subtotal

    # References the supplier entity.
    attr_accessor :supplier_id

    attr_accessor :tax_exemption_reason

    attr_accessor :total_amount

    attr_accessor :total_tax

    attr_accessor :vat_country

    attr_accessor :vat_special_case

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'attachments' => :'attachments',
        :'billing_period_end' => :'billingPeriodEnd',
        :'billing_period_start' => :'billingPeriodStart',
        :'cancellation_date' => :'cancellationDate',
        :'cancellation_invoice_id' => :'cancellationInvoiceId',
        :'cancellation_reason' => :'cancellationReason',
        :'contract_id' => :'contractId',
        :'currency' => :'currency',
        :'customer_id' => :'customerId',
        :'discount_amount' => :'discountAmount',
        :'discount_days' => :'discountDays',
        :'discount_percentage' => :'discountPercentage',
        :'document_type' => :'documentType',
        :'dunning_level' => :'dunningLevel',
        :'input_vat_amount' => :'inputVatAmount',
        :'input_vat_deductible' => :'inputVatDeductible',
        :'input_vat_percentage' => :'inputVatPercentage',
        :'introduction_text' => :'introductionText',
        :'invoice_type' => :'invoiceType',
        :'is_cancelled' => :'isCancelled',
        :'is_draft' => :'isDraft',
        :'is_eu_acquisition' => :'isEuAcquisition',
        :'is_eu_delivery' => :'isEuDelivery',
        :'is_intra_community_acquisition' => :'isIntraCommunityAcquisition',
        :'is_reverse_charge' => :'isReverseCharge',
        :'issue_date' => :'issueDate',
        :'ledger_account' => :'ledgerAccount',
        :'line_items' => :'lineItems',
        :'margin25a' => :'margin25a',
        :'margin25a_gross' => :'margin25aGross',
        :'margin25a_purchase_price' => :'margin25aPurchasePrice',
        :'notes' => :'notes',
        :'order_number' => :'orderNumber',
        :'original_pdf_path' => :'originalPdfPath',
        :'paid_amount' => :'paidAmount',
        :'payment_due_date' => :'paymentDueDate',
        :'payment_status' => :'paymentStatus',
        :'payment_terms_text' => :'paymentTermsText',
        :'preceding_sales_voucher_id' => :'precedingSalesVoucherId',
        :'preceding_sales_voucher_type' => :'precedingSalesVoucherType',
        :'receipt_confirmation_available' => :'receiptConfirmationAvailable',
        :'related_invoice_id' => :'relatedInvoiceId',
        :'relationship_type' => :'relationshipType',
        :'sender_snapshot' => :'senderSnapshot',
        :'sent_at' => :'sentAt',
        :'service_period_end' => :'servicePeriodEnd',
        :'service_period_start' => :'servicePeriodStart',
        :'status' => :'status',
        :'subtotal' => :'subtotal',
        :'supplier_id' => :'supplierId',
        :'tax_exemption_reason' => :'taxExemptionReason',
        :'total_amount' => :'totalAmount',
        :'total_tax' => :'totalTax',
        :'vat_country' => :'vatCountry',
        :'vat_special_case' => :'vatSpecialCase'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'attachments' => :'Object',
        :'billing_period_end' => :'Date',
        :'billing_period_start' => :'Date',
        :'cancellation_date' => :'Date',
        :'cancellation_invoice_id' => :'String',
        :'cancellation_reason' => :'String',
        :'contract_id' => :'String',
        :'currency' => :'CurrencyCode',
        :'customer_id' => :'String',
        :'discount_amount' => :'String',
        :'discount_days' => :'Integer',
        :'discount_percentage' => :'String',
        :'document_type' => :'DocumentType',
        :'dunning_level' => :'Integer',
        :'input_vat_amount' => :'String',
        :'input_vat_deductible' => :'Boolean',
        :'input_vat_percentage' => :'String',
        :'introduction_text' => :'String',
        :'invoice_type' => :'InvoiceType',
        :'is_cancelled' => :'Boolean',
        :'is_draft' => :'Boolean',
        :'is_eu_acquisition' => :'Boolean',
        :'is_eu_delivery' => :'Boolean',
        :'is_intra_community_acquisition' => :'Boolean',
        :'is_reverse_charge' => :'Boolean',
        :'issue_date' => :'Date',
        :'ledger_account' => :'String',
        :'line_items' => :'Object',
        :'margin25a' => :'Boolean',
        :'margin25a_gross' => :'String',
        :'margin25a_purchase_price' => :'String',
        :'notes' => :'String',
        :'order_number' => :'String',
        :'original_pdf_path' => :'String',
        :'paid_amount' => :'String',
        :'payment_due_date' => :'Date',
        :'payment_status' => :'PaymentStatus',
        :'payment_terms_text' => :'String',
        :'preceding_sales_voucher_id' => :'String',
        :'preceding_sales_voucher_type' => :'PrecedingSalesVoucherType',
        :'receipt_confirmation_available' => :'Boolean',
        :'related_invoice_id' => :'String',
        :'relationship_type' => :'String',
        :'sender_snapshot' => :'Object',
        :'sent_at' => :'Time',
        :'service_period_end' => :'Date',
        :'service_period_start' => :'Date',
        :'status' => :'InvoiceStatus',
        :'subtotal' => :'String',
        :'supplier_id' => :'String',
        :'tax_exemption_reason' => :'String',
        :'total_amount' => :'String',
        :'total_tax' => :'String',
        :'vat_country' => :'CountryCode',
        :'vat_special_case' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'attachments',
        :'billing_period_end',
        :'billing_period_start',
        :'cancellation_date',
        :'cancellation_invoice_id',
        :'cancellation_reason',
        :'contract_id',
        :'customer_id',
        :'discount_amount',
        :'discount_days',
        :'discount_percentage',
        :'input_vat_amount',
        :'input_vat_percentage',
        :'introduction_text',
        :'ledger_account',
        :'line_items',
        :'margin25a_gross',
        :'margin25a_purchase_price',
        :'notes',
        :'order_number',
        :'original_pdf_path',
        :'payment_due_date',
        :'payment_terms_text',
        :'preceding_sales_voucher_id',
        :'preceding_sales_voucher_type',
        :'related_invoice_id',
        :'relationship_type',
        :'sender_snapshot',
        :'sent_at',
        :'service_period_end',
        :'service_period_start',
        :'supplier_id',
        :'tax_exemption_reason',
        :'vat_country',
        :'vat_special_case'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::Invoice` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::Invoice`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'attachments')
        self.attachments = attributes[:'attachments']
      end

      if attributes.key?(:'billing_period_end')
        self.billing_period_end = attributes[:'billing_period_end']
      end

      if attributes.key?(:'billing_period_start')
        self.billing_period_start = attributes[:'billing_period_start']
      end

      if attributes.key?(:'cancellation_date')
        self.cancellation_date = attributes[:'cancellation_date']
      end

      if attributes.key?(:'cancellation_invoice_id')
        self.cancellation_invoice_id = attributes[:'cancellation_invoice_id']
      end

      if attributes.key?(:'cancellation_reason')
        self.cancellation_reason = attributes[:'cancellation_reason']
      end

      if attributes.key?(:'contract_id')
        self.contract_id = attributes[:'contract_id']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'discount_amount')
        self.discount_amount = attributes[:'discount_amount']
      end

      if attributes.key?(:'discount_days')
        self.discount_days = attributes[:'discount_days']
      end

      if attributes.key?(:'discount_percentage')
        self.discount_percentage = attributes[:'discount_percentage']
      end

      if attributes.key?(:'document_type')
        self.document_type = attributes[:'document_type']
      end

      if attributes.key?(:'dunning_level')
        self.dunning_level = attributes[:'dunning_level']
      end

      if attributes.key?(:'input_vat_amount')
        self.input_vat_amount = attributes[:'input_vat_amount']
      end

      if attributes.key?(:'input_vat_deductible')
        self.input_vat_deductible = attributes[:'input_vat_deductible']
      end

      if attributes.key?(:'input_vat_percentage')
        self.input_vat_percentage = attributes[:'input_vat_percentage']
      end

      if attributes.key?(:'introduction_text')
        self.introduction_text = attributes[:'introduction_text']
      end

      if attributes.key?(:'invoice_type')
        self.invoice_type = attributes[:'invoice_type']
      else
        self.invoice_type = nil
      end

      if attributes.key?(:'is_cancelled')
        self.is_cancelled = attributes[:'is_cancelled']
      end

      if attributes.key?(:'is_draft')
        self.is_draft = attributes[:'is_draft']
      end

      if attributes.key?(:'is_eu_acquisition')
        self.is_eu_acquisition = attributes[:'is_eu_acquisition']
      end

      if attributes.key?(:'is_eu_delivery')
        self.is_eu_delivery = attributes[:'is_eu_delivery']
      end

      if attributes.key?(:'is_intra_community_acquisition')
        self.is_intra_community_acquisition = attributes[:'is_intra_community_acquisition']
      end

      if attributes.key?(:'is_reverse_charge')
        self.is_reverse_charge = attributes[:'is_reverse_charge']
      end

      if attributes.key?(:'issue_date')
        self.issue_date = attributes[:'issue_date']
      else
        self.issue_date = nil
      end

      if attributes.key?(:'ledger_account')
        self.ledger_account = attributes[:'ledger_account']
      end

      if attributes.key?(:'line_items')
        self.line_items = attributes[:'line_items']
      else
        self.line_items = nil
      end

      if attributes.key?(:'margin25a')
        self.margin25a = attributes[:'margin25a']
      end

      if attributes.key?(:'margin25a_gross')
        self.margin25a_gross = attributes[:'margin25a_gross']
      end

      if attributes.key?(:'margin25a_purchase_price')
        self.margin25a_purchase_price = attributes[:'margin25a_purchase_price']
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end

      if attributes.key?(:'order_number')
        self.order_number = attributes[:'order_number']
      end

      if attributes.key?(:'original_pdf_path')
        self.original_pdf_path = attributes[:'original_pdf_path']
      end

      if attributes.key?(:'paid_amount')
        self.paid_amount = attributes[:'paid_amount']
      end

      if attributes.key?(:'payment_due_date')
        self.payment_due_date = attributes[:'payment_due_date']
      end

      if attributes.key?(:'payment_status')
        self.payment_status = attributes[:'payment_status']
      end

      if attributes.key?(:'payment_terms_text')
        self.payment_terms_text = attributes[:'payment_terms_text']
      end

      if attributes.key?(:'preceding_sales_voucher_id')
        self.preceding_sales_voucher_id = attributes[:'preceding_sales_voucher_id']
      end

      if attributes.key?(:'preceding_sales_voucher_type')
        self.preceding_sales_voucher_type = attributes[:'preceding_sales_voucher_type']
      end

      if attributes.key?(:'receipt_confirmation_available')
        self.receipt_confirmation_available = attributes[:'receipt_confirmation_available']
      end

      if attributes.key?(:'related_invoice_id')
        self.related_invoice_id = attributes[:'related_invoice_id']
      end

      if attributes.key?(:'relationship_type')
        self.relationship_type = attributes[:'relationship_type']
      end

      if attributes.key?(:'sender_snapshot')
        self.sender_snapshot = attributes[:'sender_snapshot']
      end

      if attributes.key?(:'sent_at')
        self.sent_at = attributes[:'sent_at']
      end

      if attributes.key?(:'service_period_end')
        self.service_period_end = attributes[:'service_period_end']
      end

      if attributes.key?(:'service_period_start')
        self.service_period_start = attributes[:'service_period_start']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'subtotal')
        self.subtotal = attributes[:'subtotal']
      else
        self.subtotal = nil
      end

      if attributes.key?(:'supplier_id')
        self.supplier_id = attributes[:'supplier_id']
      end

      if attributes.key?(:'tax_exemption_reason')
        self.tax_exemption_reason = attributes[:'tax_exemption_reason']
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      else
        self.total_amount = nil
      end

      if attributes.key?(:'total_tax')
        self.total_tax = attributes[:'total_tax']
      else
        self.total_tax = nil
      end

      if attributes.key?(:'vat_country')
        self.vat_country = attributes[:'vat_country']
      end

      if attributes.key?(:'vat_special_case')
        self.vat_special_case = attributes[:'vat_special_case']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @invoice_type.nil?
        invalid_properties.push('invalid value for "invoice_type", invoice_type cannot be nil.')
      end

      if @issue_date.nil?
        invalid_properties.push('invalid value for "issue_date", issue_date cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @subtotal.nil?
        invalid_properties.push('invalid value for "subtotal", subtotal cannot be nil.')
      end

      if @total_amount.nil?
        invalid_properties.push('invalid value for "total_amount", total_amount cannot be nil.')
      end

      if @total_tax.nil?
        invalid_properties.push('invalid value for "total_tax", total_tax cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @currency.nil?
      return false if @invoice_type.nil?
      return false if @issue_date.nil?
      return false if @status.nil?
      return false if @subtotal.nil?
      return false if @total_amount.nil?
      return false if @total_tax.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] invoice_type Value to be assigned
    def invoice_type=(invoice_type)
      if invoice_type.nil?
        fail ArgumentError, 'invoice_type cannot be nil'
      end

      @invoice_type = invoice_type
    end

    # Custom attribute writer method with validation
    # @param [Object] issue_date Value to be assigned
    def issue_date=(issue_date)
      if issue_date.nil?
        fail ArgumentError, 'issue_date cannot be nil'
      end

      @issue_date = issue_date
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] subtotal Value to be assigned
    def subtotal=(subtotal)
      if subtotal.nil?
        fail ArgumentError, 'subtotal cannot be nil'
      end

      @subtotal = subtotal
    end

    # Custom attribute writer method with validation
    # @param [Object] total_amount Value to be assigned
    def total_amount=(total_amount)
      if total_amount.nil?
        fail ArgumentError, 'total_amount cannot be nil'
      end

      @total_amount = total_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] total_tax Value to be assigned
    def total_tax=(total_tax)
      if total_tax.nil?
        fail ArgumentError, 'total_tax cannot be nil'
      end

      @total_tax = total_tax
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          attachments == o.attachments &&
          billing_period_end == o.billing_period_end &&
          billing_period_start == o.billing_period_start &&
          cancellation_date == o.cancellation_date &&
          cancellation_invoice_id == o.cancellation_invoice_id &&
          cancellation_reason == o.cancellation_reason &&
          contract_id == o.contract_id &&
          currency == o.currency &&
          customer_id == o.customer_id &&
          discount_amount == o.discount_amount &&
          discount_days == o.discount_days &&
          discount_percentage == o.discount_percentage &&
          document_type == o.document_type &&
          dunning_level == o.dunning_level &&
          input_vat_amount == o.input_vat_amount &&
          input_vat_deductible == o.input_vat_deductible &&
          input_vat_percentage == o.input_vat_percentage &&
          introduction_text == o.introduction_text &&
          invoice_type == o.invoice_type &&
          is_cancelled == o.is_cancelled &&
          is_draft == o.is_draft &&
          is_eu_acquisition == o.is_eu_acquisition &&
          is_eu_delivery == o.is_eu_delivery &&
          is_intra_community_acquisition == o.is_intra_community_acquisition &&
          is_reverse_charge == o.is_reverse_charge &&
          issue_date == o.issue_date &&
          ledger_account == o.ledger_account &&
          line_items == o.line_items &&
          margin25a == o.margin25a &&
          margin25a_gross == o.margin25a_gross &&
          margin25a_purchase_price == o.margin25a_purchase_price &&
          notes == o.notes &&
          order_number == o.order_number &&
          original_pdf_path == o.original_pdf_path &&
          paid_amount == o.paid_amount &&
          payment_due_date == o.payment_due_date &&
          payment_status == o.payment_status &&
          payment_terms_text == o.payment_terms_text &&
          preceding_sales_voucher_id == o.preceding_sales_voucher_id &&
          preceding_sales_voucher_type == o.preceding_sales_voucher_type &&
          receipt_confirmation_available == o.receipt_confirmation_available &&
          related_invoice_id == o.related_invoice_id &&
          relationship_type == o.relationship_type &&
          sender_snapshot == o.sender_snapshot &&
          sent_at == o.sent_at &&
          service_period_end == o.service_period_end &&
          service_period_start == o.service_period_start &&
          status == o.status &&
          subtotal == o.subtotal &&
          supplier_id == o.supplier_id &&
          tax_exemption_reason == o.tax_exemption_reason &&
          total_amount == o.total_amount &&
          total_tax == o.total_tax &&
          vat_country == o.vat_country &&
          vat_special_case == o.vat_special_case
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [attachments, billing_period_end, billing_period_start, cancellation_date, cancellation_invoice_id, cancellation_reason, contract_id, currency, customer_id, discount_amount, discount_days, discount_percentage, document_type, dunning_level, input_vat_amount, input_vat_deductible, input_vat_percentage, introduction_text, invoice_type, is_cancelled, is_draft, is_eu_acquisition, is_eu_delivery, is_intra_community_acquisition, is_reverse_charge, issue_date, ledger_account, line_items, margin25a, margin25a_gross, margin25a_purchase_price, notes, order_number, original_pdf_path, paid_amount, payment_due_date, payment_status, payment_terms_text, preceding_sales_voucher_id, preceding_sales_voucher_type, receipt_confirmation_available, related_invoice_id, relationship_type, sender_snapshot, sent_at, service_period_end, service_period_start, status, subtotal, supplier_id, tax_exemption_reason, total_amount, total_tax, vat_country, vat_special_case].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
