=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class KonzernStatus < ApiModelBase
    attr_accessor :groessenbefreit

    attr_accessor :kapitalmarktorientiert

    attr_accessor :konzernabschlusspflicht

    # Keine group_figures-Zeile für das Jahr vorhanden → keine Größenbefreiung.
    attr_accessor :missing_group_figures

    # Mutterunternehmen: mindestens eine beherrschte Beteiligung (§ 290 Abs. 1 HGB).
    attr_accessor :mutterunternehmen

    # Mutterunternehmen für die Zwischenholding-Befreiung (§ 291 HGB).
    attr_accessor :parent_name

    attr_accessor :parent_situs

    attr_accessor :participations

    attr_accessor :thresholds

    attr_accessor :year

    attr_accessor :zwischenholding_befreit

    # Hinweis zu den § 291-Voraussetzungen (EU/EWR-Sitz, geprüfter Konzernabschluss).
    attr_accessor :zwischenholding_hinweis

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'groessenbefreit' => :'groessenbefreit',
        :'kapitalmarktorientiert' => :'kapitalmarktorientiert',
        :'konzernabschlusspflicht' => :'konzernabschlusspflicht',
        :'missing_group_figures' => :'missing_group_figures',
        :'mutterunternehmen' => :'mutterunternehmen',
        :'parent_name' => :'parent_name',
        :'parent_situs' => :'parent_situs',
        :'participations' => :'participations',
        :'thresholds' => :'thresholds',
        :'year' => :'year',
        :'zwischenholding_befreit' => :'zwischenholding_befreit',
        :'zwischenholding_hinweis' => :'zwischenholding_hinweis'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'groessenbefreit' => :'Boolean',
        :'kapitalmarktorientiert' => :'Boolean',
        :'konzernabschlusspflicht' => :'Boolean',
        :'missing_group_figures' => :'Boolean',
        :'mutterunternehmen' => :'Boolean',
        :'parent_name' => :'String',
        :'parent_situs' => :'String',
        :'participations' => :'Array<KonzernBeteiligung>',
        :'thresholds' => :'KonzernThresholds',
        :'year' => :'Integer',
        :'zwischenholding_befreit' => :'Boolean',
        :'zwischenholding_hinweis' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'parent_name',
        :'parent_situs',
        :'zwischenholding_hinweis'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::KonzernStatus` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::KonzernStatus`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'groessenbefreit')
        self.groessenbefreit = attributes[:'groessenbefreit']
      else
        self.groessenbefreit = nil
      end

      if attributes.key?(:'kapitalmarktorientiert')
        self.kapitalmarktorientiert = attributes[:'kapitalmarktorientiert']
      else
        self.kapitalmarktorientiert = nil
      end

      if attributes.key?(:'konzernabschlusspflicht')
        self.konzernabschlusspflicht = attributes[:'konzernabschlusspflicht']
      else
        self.konzernabschlusspflicht = nil
      end

      if attributes.key?(:'missing_group_figures')
        self.missing_group_figures = attributes[:'missing_group_figures']
      else
        self.missing_group_figures = nil
      end

      if attributes.key?(:'mutterunternehmen')
        self.mutterunternehmen = attributes[:'mutterunternehmen']
      else
        self.mutterunternehmen = nil
      end

      if attributes.key?(:'parent_name')
        self.parent_name = attributes[:'parent_name']
      end

      if attributes.key?(:'parent_situs')
        self.parent_situs = attributes[:'parent_situs']
      end

      if attributes.key?(:'participations')
        if (value = attributes[:'participations']).is_a?(Array)
          self.participations = value
        end
      else
        self.participations = nil
      end

      if attributes.key?(:'thresholds')
        self.thresholds = attributes[:'thresholds']
      else
        self.thresholds = nil
      end

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      else
        self.year = nil
      end

      if attributes.key?(:'zwischenholding_befreit')
        self.zwischenholding_befreit = attributes[:'zwischenholding_befreit']
      else
        self.zwischenholding_befreit = nil
      end

      if attributes.key?(:'zwischenholding_hinweis')
        self.zwischenholding_hinweis = attributes[:'zwischenholding_hinweis']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @groessenbefreit.nil?
        invalid_properties.push('invalid value for "groessenbefreit", groessenbefreit cannot be nil.')
      end

      if @kapitalmarktorientiert.nil?
        invalid_properties.push('invalid value for "kapitalmarktorientiert", kapitalmarktorientiert cannot be nil.')
      end

      if @konzernabschlusspflicht.nil?
        invalid_properties.push('invalid value for "konzernabschlusspflicht", konzernabschlusspflicht cannot be nil.')
      end

      if @missing_group_figures.nil?
        invalid_properties.push('invalid value for "missing_group_figures", missing_group_figures cannot be nil.')
      end

      if @mutterunternehmen.nil?
        invalid_properties.push('invalid value for "mutterunternehmen", mutterunternehmen cannot be nil.')
      end

      if @participations.nil?
        invalid_properties.push('invalid value for "participations", participations cannot be nil.')
      end

      if @thresholds.nil?
        invalid_properties.push('invalid value for "thresholds", thresholds cannot be nil.')
      end

      if @year.nil?
        invalid_properties.push('invalid value for "year", year cannot be nil.')
      end

      if @zwischenholding_befreit.nil?
        invalid_properties.push('invalid value for "zwischenholding_befreit", zwischenholding_befreit cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @groessenbefreit.nil?
      return false if @kapitalmarktorientiert.nil?
      return false if @konzernabschlusspflicht.nil?
      return false if @missing_group_figures.nil?
      return false if @mutterunternehmen.nil?
      return false if @participations.nil?
      return false if @thresholds.nil?
      return false if @year.nil?
      return false if @zwischenholding_befreit.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] groessenbefreit Value to be assigned
    def groessenbefreit=(groessenbefreit)
      if groessenbefreit.nil?
        fail ArgumentError, 'groessenbefreit cannot be nil'
      end

      @groessenbefreit = groessenbefreit
    end

    # Custom attribute writer method with validation
    # @param [Object] kapitalmarktorientiert Value to be assigned
    def kapitalmarktorientiert=(kapitalmarktorientiert)
      if kapitalmarktorientiert.nil?
        fail ArgumentError, 'kapitalmarktorientiert cannot be nil'
      end

      @kapitalmarktorientiert = kapitalmarktorientiert
    end

    # Custom attribute writer method with validation
    # @param [Object] konzernabschlusspflicht Value to be assigned
    def konzernabschlusspflicht=(konzernabschlusspflicht)
      if konzernabschlusspflicht.nil?
        fail ArgumentError, 'konzernabschlusspflicht cannot be nil'
      end

      @konzernabschlusspflicht = konzernabschlusspflicht
    end

    # Custom attribute writer method with validation
    # @param [Object] missing_group_figures Value to be assigned
    def missing_group_figures=(missing_group_figures)
      if missing_group_figures.nil?
        fail ArgumentError, 'missing_group_figures cannot be nil'
      end

      @missing_group_figures = missing_group_figures
    end

    # Custom attribute writer method with validation
    # @param [Object] mutterunternehmen Value to be assigned
    def mutterunternehmen=(mutterunternehmen)
      if mutterunternehmen.nil?
        fail ArgumentError, 'mutterunternehmen cannot be nil'
      end

      @mutterunternehmen = mutterunternehmen
    end

    # Custom attribute writer method with validation
    # @param [Object] participations Value to be assigned
    def participations=(participations)
      if participations.nil?
        fail ArgumentError, 'participations cannot be nil'
      end

      @participations = participations
    end

    # Custom attribute writer method with validation
    # @param [Object] thresholds Value to be assigned
    def thresholds=(thresholds)
      if thresholds.nil?
        fail ArgumentError, 'thresholds cannot be nil'
      end

      @thresholds = thresholds
    end

    # Custom attribute writer method with validation
    # @param [Object] year Value to be assigned
    def year=(year)
      if year.nil?
        fail ArgumentError, 'year cannot be nil'
      end

      @year = year
    end

    # Custom attribute writer method with validation
    # @param [Object] zwischenholding_befreit Value to be assigned
    def zwischenholding_befreit=(zwischenholding_befreit)
      if zwischenholding_befreit.nil?
        fail ArgumentError, 'zwischenholding_befreit cannot be nil'
      end

      @zwischenholding_befreit = zwischenholding_befreit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          groessenbefreit == o.groessenbefreit &&
          kapitalmarktorientiert == o.kapitalmarktorientiert &&
          konzernabschlusspflicht == o.konzernabschlusspflicht &&
          missing_group_figures == o.missing_group_figures &&
          mutterunternehmen == o.mutterunternehmen &&
          parent_name == o.parent_name &&
          parent_situs == o.parent_situs &&
          participations == o.participations &&
          thresholds == o.thresholds &&
          year == o.year &&
          zwischenholding_befreit == o.zwischenholding_befreit &&
          zwischenholding_hinweis == o.zwischenholding_hinweis
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [groessenbefreit, kapitalmarktorientiert, konzernabschlusspflicht, missing_group_figures, mutterunternehmen, parent_name, parent_situs, participations, thresholds, year, zwischenholding_befreit, zwischenholding_hinweis].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
