=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class MarketplaceConnection < ApiModelBase
    attr_accessor :config

    attr_accessor :connection_id

    attr_accessor :connector_type

    attr_accessor :created_at

    attr_accessor :is_active

    attr_accessor :label

    attr_accessor :last_sync_at

    attr_accessor :platform

    attr_accessor :platform_user_id

    attr_accessor :scopes

    attr_accessor :shop_domain

    attr_accessor :shop_name

    attr_accessor :sync_status

    attr_accessor :tenant_id

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'config' => :'config',
        :'connection_id' => :'connection_id',
        :'connector_type' => :'connector_type',
        :'created_at' => :'created_at',
        :'is_active' => :'is_active',
        :'label' => :'label',
        :'last_sync_at' => :'last_sync_at',
        :'platform' => :'platform',
        :'platform_user_id' => :'platform_user_id',
        :'scopes' => :'scopes',
        :'shop_domain' => :'shop_domain',
        :'shop_name' => :'shop_name',
        :'sync_status' => :'sync_status',
        :'tenant_id' => :'tenant_id',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'config' => :'Object',
        :'connection_id' => :'String',
        :'connector_type' => :'ConnectorType',
        :'created_at' => :'Time',
        :'is_active' => :'Boolean',
        :'label' => :'String',
        :'last_sync_at' => :'Time',
        :'platform' => :'String',
        :'platform_user_id' => :'String',
        :'scopes' => :'String',
        :'shop_domain' => :'String',
        :'shop_name' => :'String',
        :'sync_status' => :'String',
        :'tenant_id' => :'String',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'config',
        :'last_sync_at',
        :'platform_user_id',
        :'scopes',
        :'shop_domain',
        :'shop_name',
        :'sync_status',
        :'updated_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::MarketplaceConnection` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::MarketplaceConnection`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'config')
        self.config = attributes[:'config']
      else
        self.config = nil
      end

      if attributes.key?(:'connection_id')
        self.connection_id = attributes[:'connection_id']
      else
        self.connection_id = nil
      end

      if attributes.key?(:'connector_type')
        self.connector_type = attributes[:'connector_type']
      else
        self.connector_type = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'is_active')
        self.is_active = attributes[:'is_active']
      else
        self.is_active = nil
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      else
        self.label = nil
      end

      if attributes.key?(:'last_sync_at')
        self.last_sync_at = attributes[:'last_sync_at']
      end

      if attributes.key?(:'platform')
        self.platform = attributes[:'platform']
      else
        self.platform = nil
      end

      if attributes.key?(:'platform_user_id')
        self.platform_user_id = attributes[:'platform_user_id']
      end

      if attributes.key?(:'scopes')
        self.scopes = attributes[:'scopes']
      end

      if attributes.key?(:'shop_domain')
        self.shop_domain = attributes[:'shop_domain']
      end

      if attributes.key?(:'shop_name')
        self.shop_name = attributes[:'shop_name']
      end

      if attributes.key?(:'sync_status')
        self.sync_status = attributes[:'sync_status']
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @connection_id.nil?
        invalid_properties.push('invalid value for "connection_id", connection_id cannot be nil.')
      end

      if @connector_type.nil?
        invalid_properties.push('invalid value for "connector_type", connector_type cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @is_active.nil?
        invalid_properties.push('invalid value for "is_active", is_active cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @platform.nil?
        invalid_properties.push('invalid value for "platform", platform cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @connection_id.nil?
      return false if @connector_type.nil?
      return false if @created_at.nil?
      return false if @is_active.nil?
      return false if @label.nil?
      return false if @platform.nil?
      return false if @tenant_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] connection_id Value to be assigned
    def connection_id=(connection_id)
      if connection_id.nil?
        fail ArgumentError, 'connection_id cannot be nil'
      end

      @connection_id = connection_id
    end

    # Custom attribute writer method with validation
    # @param [Object] connector_type Value to be assigned
    def connector_type=(connector_type)
      if connector_type.nil?
        fail ArgumentError, 'connector_type cannot be nil'
      end

      @connector_type = connector_type
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] is_active Value to be assigned
    def is_active=(is_active)
      if is_active.nil?
        fail ArgumentError, 'is_active cannot be nil'
      end

      @is_active = is_active
    end

    # Custom attribute writer method with validation
    # @param [Object] label Value to be assigned
    def label=(label)
      if label.nil?
        fail ArgumentError, 'label cannot be nil'
      end

      @label = label
    end

    # Custom attribute writer method with validation
    # @param [Object] platform Value to be assigned
    def platform=(platform)
      if platform.nil?
        fail ArgumentError, 'platform cannot be nil'
      end

      @platform = platform
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          config == o.config &&
          connection_id == o.connection_id &&
          connector_type == o.connector_type &&
          created_at == o.created_at &&
          is_active == o.is_active &&
          label == o.label &&
          last_sync_at == o.last_sync_at &&
          platform == o.platform &&
          platform_user_id == o.platform_user_id &&
          scopes == o.scopes &&
          shop_domain == o.shop_domain &&
          shop_name == o.shop_name &&
          sync_status == o.sync_status &&
          tenant_id == o.tenant_id &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [config, connection_id, connector_type, created_at, is_active, label, last_sync_at, platform, platform_user_id, scopes, shop_domain, shop_name, sync_status, tenant_id, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
