=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class OpenItem < ApiModelBase
    attr_accessor :amount_due

    attr_accessor :amount_paid

    attr_accessor :customer_id

    attr_accessor :days_overdue

    attr_accessor :due_date

    attr_accessor :invoice_id

    attr_accessor :invoice_number

    attr_accessor :issue_date

    attr_accessor :open_amount

    attr_accessor :reminder_level

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount_due' => :'amount_due',
        :'amount_paid' => :'amount_paid',
        :'customer_id' => :'customer_id',
        :'days_overdue' => :'days_overdue',
        :'due_date' => :'due_date',
        :'invoice_id' => :'invoice_id',
        :'invoice_number' => :'invoice_number',
        :'issue_date' => :'issue_date',
        :'open_amount' => :'open_amount',
        :'reminder_level' => :'reminder_level'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount_due' => :'String',
        :'amount_paid' => :'String',
        :'customer_id' => :'String',
        :'days_overdue' => :'Integer',
        :'due_date' => :'String',
        :'invoice_id' => :'String',
        :'invoice_number' => :'String',
        :'issue_date' => :'String',
        :'open_amount' => :'String',
        :'reminder_level' => :'ReminderLevel'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'customer_id',
        :'days_overdue',
        :'due_date',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::OpenItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::OpenItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount_due')
        self.amount_due = attributes[:'amount_due']
      else
        self.amount_due = nil
      end

      if attributes.key?(:'amount_paid')
        self.amount_paid = attributes[:'amount_paid']
      else
        self.amount_paid = nil
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'days_overdue')
        self.days_overdue = attributes[:'days_overdue']
      end

      if attributes.key?(:'due_date')
        self.due_date = attributes[:'due_date']
      end

      if attributes.key?(:'invoice_id')
        self.invoice_id = attributes[:'invoice_id']
      else
        self.invoice_id = nil
      end

      if attributes.key?(:'invoice_number')
        self.invoice_number = attributes[:'invoice_number']
      else
        self.invoice_number = nil
      end

      if attributes.key?(:'issue_date')
        self.issue_date = attributes[:'issue_date']
      else
        self.issue_date = nil
      end

      if attributes.key?(:'open_amount')
        self.open_amount = attributes[:'open_amount']
      else
        self.open_amount = nil
      end

      if attributes.key?(:'reminder_level')
        self.reminder_level = attributes[:'reminder_level']
      else
        self.reminder_level = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @amount_due.nil?
        invalid_properties.push('invalid value for "amount_due", amount_due cannot be nil.')
      end

      if @amount_paid.nil?
        invalid_properties.push('invalid value for "amount_paid", amount_paid cannot be nil.')
      end

      if @invoice_id.nil?
        invalid_properties.push('invalid value for "invoice_id", invoice_id cannot be nil.')
      end

      if @invoice_number.nil?
        invalid_properties.push('invalid value for "invoice_number", invoice_number cannot be nil.')
      end

      if @issue_date.nil?
        invalid_properties.push('invalid value for "issue_date", issue_date cannot be nil.')
      end

      if @open_amount.nil?
        invalid_properties.push('invalid value for "open_amount", open_amount cannot be nil.')
      end

      if @reminder_level.nil?
        invalid_properties.push('invalid value for "reminder_level", reminder_level cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @amount_due.nil?
      return false if @amount_paid.nil?
      return false if @invoice_id.nil?
      return false if @invoice_number.nil?
      return false if @issue_date.nil?
      return false if @open_amount.nil?
      return false if @reminder_level.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount_due Value to be assigned
    def amount_due=(amount_due)
      if amount_due.nil?
        fail ArgumentError, 'amount_due cannot be nil'
      end

      @amount_due = amount_due
    end

    # Custom attribute writer method with validation
    # @param [Object] amount_paid Value to be assigned
    def amount_paid=(amount_paid)
      if amount_paid.nil?
        fail ArgumentError, 'amount_paid cannot be nil'
      end

      @amount_paid = amount_paid
    end

    # Custom attribute writer method with validation
    # @param [Object] invoice_id Value to be assigned
    def invoice_id=(invoice_id)
      if invoice_id.nil?
        fail ArgumentError, 'invoice_id cannot be nil'
      end

      @invoice_id = invoice_id
    end

    # Custom attribute writer method with validation
    # @param [Object] invoice_number Value to be assigned
    def invoice_number=(invoice_number)
      if invoice_number.nil?
        fail ArgumentError, 'invoice_number cannot be nil'
      end

      @invoice_number = invoice_number
    end

    # Custom attribute writer method with validation
    # @param [Object] issue_date Value to be assigned
    def issue_date=(issue_date)
      if issue_date.nil?
        fail ArgumentError, 'issue_date cannot be nil'
      end

      @issue_date = issue_date
    end

    # Custom attribute writer method with validation
    # @param [Object] open_amount Value to be assigned
    def open_amount=(open_amount)
      if open_amount.nil?
        fail ArgumentError, 'open_amount cannot be nil'
      end

      @open_amount = open_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] reminder_level Value to be assigned
    def reminder_level=(reminder_level)
      if reminder_level.nil?
        fail ArgumentError, 'reminder_level cannot be nil'
      end

      @reminder_level = reminder_level
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount_due == o.amount_due &&
          amount_paid == o.amount_paid &&
          customer_id == o.customer_id &&
          days_overdue == o.days_overdue &&
          due_date == o.due_date &&
          invoice_id == o.invoice_id &&
          invoice_number == o.invoice_number &&
          issue_date == o.issue_date &&
          open_amount == o.open_amount &&
          reminder_level == o.reminder_level
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount_due, amount_paid, customer_id, days_overdue, due_date, invoice_id, invoice_number, issue_date, open_amount, reminder_level].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
