=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class PayrollRunApi < ApiModelBase
    attr_accessor :approved_at

    attr_accessor :approved_by

    attr_accessor :created_at

    attr_accessor :entries

    attr_accessor :month

    attr_accessor :payment_date

    attr_accessor :period_label

    attr_accessor :run_id

    attr_accessor :status

    attr_accessor :tenant_id

    attr_accessor :total_employee_count

    attr_accessor :total_employer_cost

    attr_accessor :total_gross

    attr_accessor :total_net

    attr_accessor :total_social_security

    attr_accessor :total_taxes

    attr_accessor :updated_at

    attr_accessor :year

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'approved_at' => :'approved_at',
        :'approved_by' => :'approved_by',
        :'created_at' => :'created_at',
        :'entries' => :'entries',
        :'month' => :'month',
        :'payment_date' => :'payment_date',
        :'period_label' => :'period_label',
        :'run_id' => :'run_id',
        :'status' => :'status',
        :'tenant_id' => :'tenant_id',
        :'total_employee_count' => :'total_employee_count',
        :'total_employer_cost' => :'total_employer_cost',
        :'total_gross' => :'total_gross',
        :'total_net' => :'total_net',
        :'total_social_security' => :'total_social_security',
        :'total_taxes' => :'total_taxes',
        :'updated_at' => :'updated_at',
        :'year' => :'year'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'approved_at' => :'Time',
        :'approved_by' => :'String',
        :'created_at' => :'Time',
        :'entries' => :'Array<PayrollEntryApi>',
        :'month' => :'Integer',
        :'payment_date' => :'Date',
        :'period_label' => :'String',
        :'run_id' => :'String',
        :'status' => :'PayrollRunStatus',
        :'tenant_id' => :'String',
        :'total_employee_count' => :'Integer',
        :'total_employer_cost' => :'String',
        :'total_gross' => :'String',
        :'total_net' => :'String',
        :'total_social_security' => :'String',
        :'total_taxes' => :'String',
        :'updated_at' => :'Time',
        :'year' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'approved_at',
        :'approved_by',
        :'payment_date',
        :'updated_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::PayrollRunApi` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::PayrollRunApi`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'approved_at')
        self.approved_at = attributes[:'approved_at']
      end

      if attributes.key?(:'approved_by')
        self.approved_by = attributes[:'approved_by']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'entries')
        if (value = attributes[:'entries']).is_a?(Array)
          self.entries = value
        end
      else
        self.entries = nil
      end

      if attributes.key?(:'month')
        self.month = attributes[:'month']
      else
        self.month = nil
      end

      if attributes.key?(:'payment_date')
        self.payment_date = attributes[:'payment_date']
      end

      if attributes.key?(:'period_label')
        self.period_label = attributes[:'period_label']
      else
        self.period_label = nil
      end

      if attributes.key?(:'run_id')
        self.run_id = attributes[:'run_id']
      else
        self.run_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'total_employee_count')
        self.total_employee_count = attributes[:'total_employee_count']
      else
        self.total_employee_count = nil
      end

      if attributes.key?(:'total_employer_cost')
        self.total_employer_cost = attributes[:'total_employer_cost']
      else
        self.total_employer_cost = nil
      end

      if attributes.key?(:'total_gross')
        self.total_gross = attributes[:'total_gross']
      else
        self.total_gross = nil
      end

      if attributes.key?(:'total_net')
        self.total_net = attributes[:'total_net']
      else
        self.total_net = nil
      end

      if attributes.key?(:'total_social_security')
        self.total_social_security = attributes[:'total_social_security']
      else
        self.total_social_security = nil
      end

      if attributes.key?(:'total_taxes')
        self.total_taxes = attributes[:'total_taxes']
      else
        self.total_taxes = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      else
        self.year = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @entries.nil?
        invalid_properties.push('invalid value for "entries", entries cannot be nil.')
      end

      if @month.nil?
        invalid_properties.push('invalid value for "month", month cannot be nil.')
      end

      if @period_label.nil?
        invalid_properties.push('invalid value for "period_label", period_label cannot be nil.')
      end

      if @run_id.nil?
        invalid_properties.push('invalid value for "run_id", run_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @total_employee_count.nil?
        invalid_properties.push('invalid value for "total_employee_count", total_employee_count cannot be nil.')
      end

      if @total_employer_cost.nil?
        invalid_properties.push('invalid value for "total_employer_cost", total_employer_cost cannot be nil.')
      end

      if @total_gross.nil?
        invalid_properties.push('invalid value for "total_gross", total_gross cannot be nil.')
      end

      if @total_net.nil?
        invalid_properties.push('invalid value for "total_net", total_net cannot be nil.')
      end

      if @total_social_security.nil?
        invalid_properties.push('invalid value for "total_social_security", total_social_security cannot be nil.')
      end

      if @total_taxes.nil?
        invalid_properties.push('invalid value for "total_taxes", total_taxes cannot be nil.')
      end

      if @year.nil?
        invalid_properties.push('invalid value for "year", year cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @created_at.nil?
      return false if @entries.nil?
      return false if @month.nil?
      return false if @period_label.nil?
      return false if @run_id.nil?
      return false if @status.nil?
      return false if @tenant_id.nil?
      return false if @total_employee_count.nil?
      return false if @total_employer_cost.nil?
      return false if @total_gross.nil?
      return false if @total_net.nil?
      return false if @total_social_security.nil?
      return false if @total_taxes.nil?
      return false if @year.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] entries Value to be assigned
    def entries=(entries)
      if entries.nil?
        fail ArgumentError, 'entries cannot be nil'
      end

      @entries = entries
    end

    # Custom attribute writer method with validation
    # @param [Object] month Value to be assigned
    def month=(month)
      if month.nil?
        fail ArgumentError, 'month cannot be nil'
      end

      @month = month
    end

    # Custom attribute writer method with validation
    # @param [Object] period_label Value to be assigned
    def period_label=(period_label)
      if period_label.nil?
        fail ArgumentError, 'period_label cannot be nil'
      end

      @period_label = period_label
    end

    # Custom attribute writer method with validation
    # @param [Object] run_id Value to be assigned
    def run_id=(run_id)
      if run_id.nil?
        fail ArgumentError, 'run_id cannot be nil'
      end

      @run_id = run_id
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] total_employee_count Value to be assigned
    def total_employee_count=(total_employee_count)
      if total_employee_count.nil?
        fail ArgumentError, 'total_employee_count cannot be nil'
      end

      @total_employee_count = total_employee_count
    end

    # Custom attribute writer method with validation
    # @param [Object] total_employer_cost Value to be assigned
    def total_employer_cost=(total_employer_cost)
      if total_employer_cost.nil?
        fail ArgumentError, 'total_employer_cost cannot be nil'
      end

      @total_employer_cost = total_employer_cost
    end

    # Custom attribute writer method with validation
    # @param [Object] total_gross Value to be assigned
    def total_gross=(total_gross)
      if total_gross.nil?
        fail ArgumentError, 'total_gross cannot be nil'
      end

      @total_gross = total_gross
    end

    # Custom attribute writer method with validation
    # @param [Object] total_net Value to be assigned
    def total_net=(total_net)
      if total_net.nil?
        fail ArgumentError, 'total_net cannot be nil'
      end

      @total_net = total_net
    end

    # Custom attribute writer method with validation
    # @param [Object] total_social_security Value to be assigned
    def total_social_security=(total_social_security)
      if total_social_security.nil?
        fail ArgumentError, 'total_social_security cannot be nil'
      end

      @total_social_security = total_social_security
    end

    # Custom attribute writer method with validation
    # @param [Object] total_taxes Value to be assigned
    def total_taxes=(total_taxes)
      if total_taxes.nil?
        fail ArgumentError, 'total_taxes cannot be nil'
      end

      @total_taxes = total_taxes
    end

    # Custom attribute writer method with validation
    # @param [Object] year Value to be assigned
    def year=(year)
      if year.nil?
        fail ArgumentError, 'year cannot be nil'
      end

      @year = year
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          approved_at == o.approved_at &&
          approved_by == o.approved_by &&
          created_at == o.created_at &&
          entries == o.entries &&
          month == o.month &&
          payment_date == o.payment_date &&
          period_label == o.period_label &&
          run_id == o.run_id &&
          status == o.status &&
          tenant_id == o.tenant_id &&
          total_employee_count == o.total_employee_count &&
          total_employer_cost == o.total_employer_cost &&
          total_gross == o.total_gross &&
          total_net == o.total_net &&
          total_social_security == o.total_social_security &&
          total_taxes == o.total_taxes &&
          updated_at == o.updated_at &&
          year == o.year
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [approved_at, approved_by, created_at, entries, month, payment_date, period_label, run_id, status, tenant_id, total_employee_count, total_employer_cost, total_gross, total_net, total_social_security, total_taxes, updated_at, year].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
