=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class ProductCreate < ApiModelBase
    attr_accessor :availability

    attr_accessor :barcode

    attr_accessor :brand

    attr_accessor :category_id

    attr_accessor :condition

    attr_accessor :default_ledger_account

    attr_accessor :default_price

    # References the price formula entity.
    attr_accessor :default_price_formula_id

    attr_accessor :default_tax_rate

    attr_accessor :description

    attr_accessor :gtin

    attr_accessor :height

    attr_accessor :image_link

    attr_accessor :images

    attr_accessor :is_taxable

    attr_accessor :length

    attr_accessor :link

    # Target stock level used by reorder proposals.
    attr_accessor :max_stock

    # Reorder point — when stock falls below this, a reorder is suggested.
    attr_accessor :min_stock

    attr_accessor :mpn

    attr_accessor :name

    attr_accessor :package_height

    attr_accessor :package_length

    attr_accessor :package_weight_unit

    attr_accessor :package_weight_value

    attr_accessor :package_width

    attr_accessor :product_code

    attr_accessor :product_type

    attr_accessor :purchase_price

    # Suggested purchase quantity when a reorder proposal is created.
    attr_accessor :reorder_quantity

    attr_accessor :sale_price

    attr_accessor :shipping_price

    attr_accessor :shipping_requires_insurance

    attr_accessor :sku

    attr_accessor :stock_quantity

    attr_accessor :tags

    attr_accessor :tax_price

    # Whether this product requires batch (Chargennummer) tracking.
    attr_accessor :track_batch

    # Whether this product requires serial-number tracking.
    attr_accessor :track_serial

    attr_accessor :unit

    attr_accessor :weight_unit

    attr_accessor :weight_value

    attr_accessor :width

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'availability' => :'availability',
        :'barcode' => :'barcode',
        :'brand' => :'brand',
        :'category_id' => :'categoryId',
        :'condition' => :'condition',
        :'default_ledger_account' => :'defaultLedgerAccount',
        :'default_price' => :'defaultPrice',
        :'default_price_formula_id' => :'defaultPriceFormulaId',
        :'default_tax_rate' => :'defaultTaxRate',
        :'description' => :'description',
        :'gtin' => :'gtin',
        :'height' => :'height',
        :'image_link' => :'imageLink',
        :'images' => :'images',
        :'is_taxable' => :'isTaxable',
        :'length' => :'length',
        :'link' => :'link',
        :'max_stock' => :'maxStock',
        :'min_stock' => :'minStock',
        :'mpn' => :'mpn',
        :'name' => :'name',
        :'package_height' => :'packageHeight',
        :'package_length' => :'packageLength',
        :'package_weight_unit' => :'packageWeightUnit',
        :'package_weight_value' => :'packageWeightValue',
        :'package_width' => :'packageWidth',
        :'product_code' => :'productCode',
        :'product_type' => :'productType',
        :'purchase_price' => :'purchasePrice',
        :'reorder_quantity' => :'reorderQuantity',
        :'sale_price' => :'salePrice',
        :'shipping_price' => :'shippingPrice',
        :'shipping_requires_insurance' => :'shippingRequiresInsurance',
        :'sku' => :'sku',
        :'stock_quantity' => :'stockQuantity',
        :'tags' => :'tags',
        :'tax_price' => :'taxPrice',
        :'track_batch' => :'trackBatch',
        :'track_serial' => :'trackSerial',
        :'unit' => :'unit',
        :'weight_unit' => :'weightUnit',
        :'weight_value' => :'weightValue',
        :'width' => :'width'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'availability' => :'String',
        :'barcode' => :'String',
        :'brand' => :'String',
        :'category_id' => :'String',
        :'condition' => :'String',
        :'default_ledger_account' => :'String',
        :'default_price' => :'String',
        :'default_price_formula_id' => :'String',
        :'default_tax_rate' => :'String',
        :'description' => :'String',
        :'gtin' => :'String',
        :'height' => :'String',
        :'image_link' => :'String',
        :'images' => :'Object',
        :'is_taxable' => :'Boolean',
        :'length' => :'String',
        :'link' => :'String',
        :'max_stock' => :'Integer',
        :'min_stock' => :'Integer',
        :'mpn' => :'String',
        :'name' => :'String',
        :'package_height' => :'String',
        :'package_length' => :'String',
        :'package_weight_unit' => :'String',
        :'package_weight_value' => :'String',
        :'package_width' => :'String',
        :'product_code' => :'String',
        :'product_type' => :'String',
        :'purchase_price' => :'String',
        :'reorder_quantity' => :'Integer',
        :'sale_price' => :'String',
        :'shipping_price' => :'String',
        :'shipping_requires_insurance' => :'Boolean',
        :'sku' => :'String',
        :'stock_quantity' => :'Integer',
        :'tags' => :'Object',
        :'tax_price' => :'String',
        :'track_batch' => :'Boolean',
        :'track_serial' => :'Boolean',
        :'unit' => :'Object',
        :'weight_unit' => :'String',
        :'weight_value' => :'String',
        :'width' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'availability',
        :'barcode',
        :'brand',
        :'category_id',
        :'condition',
        :'default_ledger_account',
        :'default_price',
        :'default_price_formula_id',
        :'default_tax_rate',
        :'description',
        :'gtin',
        :'height',
        :'image_link',
        :'images',
        :'length',
        :'link',
        :'max_stock',
        :'min_stock',
        :'mpn',
        :'package_height',
        :'package_length',
        :'package_weight_unit',
        :'package_weight_value',
        :'package_width',
        :'product_type',
        :'purchase_price',
        :'reorder_quantity',
        :'sale_price',
        :'shipping_price',
        :'shipping_requires_insurance',
        :'stock_quantity',
        :'tags',
        :'tax_price',
        :'unit',
        :'weight_unit',
        :'weight_value',
        :'width'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::ProductCreate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::ProductCreate`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'availability')
        self.availability = attributes[:'availability']
      end

      if attributes.key?(:'barcode')
        self.barcode = attributes[:'barcode']
      end

      if attributes.key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.key?(:'category_id')
        self.category_id = attributes[:'category_id']
      end

      if attributes.key?(:'condition')
        self.condition = attributes[:'condition']
      end

      if attributes.key?(:'default_ledger_account')
        self.default_ledger_account = attributes[:'default_ledger_account']
      end

      if attributes.key?(:'default_price')
        self.default_price = attributes[:'default_price']
      end

      if attributes.key?(:'default_price_formula_id')
        self.default_price_formula_id = attributes[:'default_price_formula_id']
      end

      if attributes.key?(:'default_tax_rate')
        self.default_tax_rate = attributes[:'default_tax_rate']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'gtin')
        self.gtin = attributes[:'gtin']
      end

      if attributes.key?(:'height')
        self.height = attributes[:'height']
      end

      if attributes.key?(:'image_link')
        self.image_link = attributes[:'image_link']
      end

      if attributes.key?(:'images')
        self.images = attributes[:'images']
      end

      if attributes.key?(:'is_taxable')
        self.is_taxable = attributes[:'is_taxable']
      end

      if attributes.key?(:'length')
        self.length = attributes[:'length']
      end

      if attributes.key?(:'link')
        self.link = attributes[:'link']
      end

      if attributes.key?(:'max_stock')
        self.max_stock = attributes[:'max_stock']
      end

      if attributes.key?(:'min_stock')
        self.min_stock = attributes[:'min_stock']
      end

      if attributes.key?(:'mpn')
        self.mpn = attributes[:'mpn']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'package_height')
        self.package_height = attributes[:'package_height']
      end

      if attributes.key?(:'package_length')
        self.package_length = attributes[:'package_length']
      end

      if attributes.key?(:'package_weight_unit')
        self.package_weight_unit = attributes[:'package_weight_unit']
      end

      if attributes.key?(:'package_weight_value')
        self.package_weight_value = attributes[:'package_weight_value']
      end

      if attributes.key?(:'package_width')
        self.package_width = attributes[:'package_width']
      end

      if attributes.key?(:'product_code')
        self.product_code = attributes[:'product_code']
      else
        self.product_code = nil
      end

      if attributes.key?(:'product_type')
        self.product_type = attributes[:'product_type']
      end

      if attributes.key?(:'purchase_price')
        self.purchase_price = attributes[:'purchase_price']
      end

      if attributes.key?(:'reorder_quantity')
        self.reorder_quantity = attributes[:'reorder_quantity']
      end

      if attributes.key?(:'sale_price')
        self.sale_price = attributes[:'sale_price']
      end

      if attributes.key?(:'shipping_price')
        self.shipping_price = attributes[:'shipping_price']
      end

      if attributes.key?(:'shipping_requires_insurance')
        self.shipping_requires_insurance = attributes[:'shipping_requires_insurance']
      end

      if attributes.key?(:'sku')
        self.sku = attributes[:'sku']
      else
        self.sku = nil
      end

      if attributes.key?(:'stock_quantity')
        self.stock_quantity = attributes[:'stock_quantity']
      end

      if attributes.key?(:'tags')
        self.tags = attributes[:'tags']
      end

      if attributes.key?(:'tax_price')
        self.tax_price = attributes[:'tax_price']
      end

      if attributes.key?(:'track_batch')
        self.track_batch = attributes[:'track_batch']
      end

      if attributes.key?(:'track_serial')
        self.track_serial = attributes[:'track_serial']
      end

      if attributes.key?(:'unit')
        self.unit = attributes[:'unit']
      end

      if attributes.key?(:'weight_unit')
        self.weight_unit = attributes[:'weight_unit']
      end

      if attributes.key?(:'weight_value')
        self.weight_value = attributes[:'weight_value']
      end

      if attributes.key?(:'width')
        self.width = attributes[:'width']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@barcode.nil? && @barcode.to_s.length > 100
        invalid_properties.push('invalid value for "barcode", the character length must be smaller than or equal to 100.')
      end

      if !@brand.nil? && @brand.to_s.length > 255
        invalid_properties.push('invalid value for "brand", the character length must be smaller than or equal to 255.')
      end

      if !@category_id.nil? && @category_id.to_s.length > 50
        invalid_properties.push('invalid value for "category_id", the character length must be smaller than or equal to 50.')
      end

      if !@default_ledger_account.nil? && @default_ledger_account.to_s.length > 50
        invalid_properties.push('invalid value for "default_ledger_account", the character length must be smaller than or equal to 50.')
      end

      if !@description.nil? && @description.to_s.length > 5000
        invalid_properties.push('invalid value for "description", the character length must be smaller than or equal to 5000.')
      end

      if !@gtin.nil? && @gtin.to_s.length > 50
        invalid_properties.push('invalid value for "gtin", the character length must be smaller than or equal to 50.')
      end

      if !@image_link.nil? && @image_link.to_s.length > 2048
        invalid_properties.push('invalid value for "image_link", the character length must be smaller than or equal to 2048.')
      end

      if !@link.nil? && @link.to_s.length > 2048
        invalid_properties.push('invalid value for "link", the character length must be smaller than or equal to 2048.')
      end

      if !@mpn.nil? && @mpn.to_s.length > 100
        invalid_properties.push('invalid value for "mpn", the character length must be smaller than or equal to 100.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 255
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 255.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if !@package_weight_unit.nil? && @package_weight_unit.to_s.length > 10
        invalid_properties.push('invalid value for "package_weight_unit", the character length must be smaller than or equal to 10.')
      end

      if @product_code.nil?
        invalid_properties.push('invalid value for "product_code", product_code cannot be nil.')
      end

      if @product_code.to_s.length > 100
        invalid_properties.push('invalid value for "product_code", the character length must be smaller than or equal to 100.')
      end

      if @product_code.to_s.length < 1
        invalid_properties.push('invalid value for "product_code", the character length must be greater than or equal to 1.')
      end

      if !@product_type.nil? && @product_type.to_s.length > 50
        invalid_properties.push('invalid value for "product_type", the character length must be smaller than or equal to 50.')
      end

      if @sku.nil?
        invalid_properties.push('invalid value for "sku", sku cannot be nil.')
      end

      if @sku.to_s.length > 100
        invalid_properties.push('invalid value for "sku", the character length must be smaller than or equal to 100.')
      end

      if @sku.to_s.length < 1
        invalid_properties.push('invalid value for "sku", the character length must be greater than or equal to 1.')
      end

      if !@weight_unit.nil? && @weight_unit.to_s.length > 10
        invalid_properties.push('invalid value for "weight_unit", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@barcode.nil? && @barcode.to_s.length > 100
      return false if !@brand.nil? && @brand.to_s.length > 255
      return false if !@category_id.nil? && @category_id.to_s.length > 50
      return false if !@default_ledger_account.nil? && @default_ledger_account.to_s.length > 50
      return false if !@description.nil? && @description.to_s.length > 5000
      return false if !@gtin.nil? && @gtin.to_s.length > 50
      return false if !@image_link.nil? && @image_link.to_s.length > 2048
      return false if !@link.nil? && @link.to_s.length > 2048
      return false if !@mpn.nil? && @mpn.to_s.length > 100
      return false if @name.nil?
      return false if @name.to_s.length > 255
      return false if @name.to_s.length < 1
      return false if !@package_weight_unit.nil? && @package_weight_unit.to_s.length > 10
      return false if @product_code.nil?
      return false if @product_code.to_s.length > 100
      return false if @product_code.to_s.length < 1
      return false if !@product_type.nil? && @product_type.to_s.length > 50
      return false if @sku.nil?
      return false if @sku.to_s.length > 100
      return false if @sku.to_s.length < 1
      return false if !@weight_unit.nil? && @weight_unit.to_s.length > 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] barcode Value to be assigned
    def barcode=(barcode)
      if !barcode.nil? && barcode.to_s.length > 100
        fail ArgumentError, 'invalid value for "barcode", the character length must be smaller than or equal to 100.'
      end

      @barcode = barcode
    end

    # Custom attribute writer method with validation
    # @param [Object] brand Value to be assigned
    def brand=(brand)
      if !brand.nil? && brand.to_s.length > 255
        fail ArgumentError, 'invalid value for "brand", the character length must be smaller than or equal to 255.'
      end

      @brand = brand
    end

    # Custom attribute writer method with validation
    # @param [Object] category_id Value to be assigned
    def category_id=(category_id)
      if !category_id.nil? && category_id.to_s.length > 50
        fail ArgumentError, 'invalid value for "category_id", the character length must be smaller than or equal to 50.'
      end

      @category_id = category_id
    end

    # Custom attribute writer method with validation
    # @param [Object] default_ledger_account Value to be assigned
    def default_ledger_account=(default_ledger_account)
      if !default_ledger_account.nil? && default_ledger_account.to_s.length > 50
        fail ArgumentError, 'invalid value for "default_ledger_account", the character length must be smaller than or equal to 50.'
      end

      @default_ledger_account = default_ledger_account
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if !description.nil? && description.to_s.length > 5000
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 5000.'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] gtin Value to be assigned
    def gtin=(gtin)
      if !gtin.nil? && gtin.to_s.length > 50
        fail ArgumentError, 'invalid value for "gtin", the character length must be smaller than or equal to 50.'
      end

      @gtin = gtin
    end

    # Custom attribute writer method with validation
    # @param [Object] image_link Value to be assigned
    def image_link=(image_link)
      if !image_link.nil? && image_link.to_s.length > 2048
        fail ArgumentError, 'invalid value for "image_link", the character length must be smaller than or equal to 2048.'
      end

      @image_link = image_link
    end

    # Custom attribute writer method with validation
    # @param [Object] link Value to be assigned
    def link=(link)
      if !link.nil? && link.to_s.length > 2048
        fail ArgumentError, 'invalid value for "link", the character length must be smaller than or equal to 2048.'
      end

      @link = link
    end

    # Custom attribute writer method with validation
    # @param [Object] mpn Value to be assigned
    def mpn=(mpn)
      if !mpn.nil? && mpn.to_s.length > 100
        fail ArgumentError, 'invalid value for "mpn", the character length must be smaller than or equal to 100.'
      end

      @mpn = mpn
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 255
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 255.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] package_weight_unit Value to be assigned
    def package_weight_unit=(package_weight_unit)
      if !package_weight_unit.nil? && package_weight_unit.to_s.length > 10
        fail ArgumentError, 'invalid value for "package_weight_unit", the character length must be smaller than or equal to 10.'
      end

      @package_weight_unit = package_weight_unit
    end

    # Custom attribute writer method with validation
    # @param [Object] product_code Value to be assigned
    def product_code=(product_code)
      if product_code.nil?
        fail ArgumentError, 'product_code cannot be nil'
      end

      if product_code.to_s.length > 100
        fail ArgumentError, 'invalid value for "product_code", the character length must be smaller than or equal to 100.'
      end

      if product_code.to_s.length < 1
        fail ArgumentError, 'invalid value for "product_code", the character length must be greater than or equal to 1.'
      end

      @product_code = product_code
    end

    # Custom attribute writer method with validation
    # @param [Object] product_type Value to be assigned
    def product_type=(product_type)
      if !product_type.nil? && product_type.to_s.length > 50
        fail ArgumentError, 'invalid value for "product_type", the character length must be smaller than or equal to 50.'
      end

      @product_type = product_type
    end

    # Custom attribute writer method with validation
    # @param [Object] sku Value to be assigned
    def sku=(sku)
      if sku.nil?
        fail ArgumentError, 'sku cannot be nil'
      end

      if sku.to_s.length > 100
        fail ArgumentError, 'invalid value for "sku", the character length must be smaller than or equal to 100.'
      end

      if sku.to_s.length < 1
        fail ArgumentError, 'invalid value for "sku", the character length must be greater than or equal to 1.'
      end

      @sku = sku
    end

    # Custom attribute writer method with validation
    # @param [Object] weight_unit Value to be assigned
    def weight_unit=(weight_unit)
      if !weight_unit.nil? && weight_unit.to_s.length > 10
        fail ArgumentError, 'invalid value for "weight_unit", the character length must be smaller than or equal to 10.'
      end

      @weight_unit = weight_unit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          availability == o.availability &&
          barcode == o.barcode &&
          brand == o.brand &&
          category_id == o.category_id &&
          condition == o.condition &&
          default_ledger_account == o.default_ledger_account &&
          default_price == o.default_price &&
          default_price_formula_id == o.default_price_formula_id &&
          default_tax_rate == o.default_tax_rate &&
          description == o.description &&
          gtin == o.gtin &&
          height == o.height &&
          image_link == o.image_link &&
          images == o.images &&
          is_taxable == o.is_taxable &&
          length == o.length &&
          link == o.link &&
          max_stock == o.max_stock &&
          min_stock == o.min_stock &&
          mpn == o.mpn &&
          name == o.name &&
          package_height == o.package_height &&
          package_length == o.package_length &&
          package_weight_unit == o.package_weight_unit &&
          package_weight_value == o.package_weight_value &&
          package_width == o.package_width &&
          product_code == o.product_code &&
          product_type == o.product_type &&
          purchase_price == o.purchase_price &&
          reorder_quantity == o.reorder_quantity &&
          sale_price == o.sale_price &&
          shipping_price == o.shipping_price &&
          shipping_requires_insurance == o.shipping_requires_insurance &&
          sku == o.sku &&
          stock_quantity == o.stock_quantity &&
          tags == o.tags &&
          tax_price == o.tax_price &&
          track_batch == o.track_batch &&
          track_serial == o.track_serial &&
          unit == o.unit &&
          weight_unit == o.weight_unit &&
          weight_value == o.weight_value &&
          width == o.width
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [availability, barcode, brand, category_id, condition, default_ledger_account, default_price, default_price_formula_id, default_tax_rate, description, gtin, height, image_link, images, is_taxable, length, link, max_stock, min_stock, mpn, name, package_height, package_length, package_weight_unit, package_weight_value, package_width, product_code, product_type, purchase_price, reorder_quantity, sale_price, shipping_price, shipping_requires_insurance, sku, stock_quantity, tags, tax_price, track_batch, track_serial, unit, weight_unit, weight_value, width].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
