=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class ReferenceType
    GOODS_RECEIPT = "goods_receipt".freeze
    PRODUCTION_ORDER = "production_order".freeze
    TRANSFER_IN = "transfer_in".freeze
    STOCK_TRANSFER = "stock_transfer".freeze
    RETURN_ORDER = "return_order".freeze
    INVENTORY_COUNT = "inventory_count".freeze

    def self.all_vars
      @all_vars ||= [GOODS_RECEIPT, PRODUCTION_ORDER, TRANSFER_IN, STOCK_TRANSFER, RETURN_ORDER, INVENTORY_COUNT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ReferenceType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ReferenceType"
    end
  end
end
