=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  # A single replenishment suggestion.
  class ReplenishmentSuggestionLine < ApiModelBase
    # Current stock in the target warehouse.
    attr_accessor :current_stock

    attr_accessor :max_stock

    attr_accessor :min_stock

    attr_accessor :product_id

    attr_accessor :product_name

    attr_accessor :sku

    # Surplus available in the source warehouse (above its target).
    attr_accessor :source_available

    attr_accessor :source_warehouse_id

    attr_accessor :suggested_quantity

    attr_accessor :target_warehouse_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'current_stock' => :'currentStock',
        :'max_stock' => :'maxStock',
        :'min_stock' => :'minStock',
        :'product_id' => :'productId',
        :'product_name' => :'productName',
        :'sku' => :'sku',
        :'source_available' => :'sourceAvailable',
        :'source_warehouse_id' => :'sourceWarehouseId',
        :'suggested_quantity' => :'suggestedQuantity',
        :'target_warehouse_id' => :'targetWarehouseId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'current_stock' => :'Integer',
        :'max_stock' => :'Integer',
        :'min_stock' => :'Integer',
        :'product_id' => :'String',
        :'product_name' => :'String',
        :'sku' => :'String',
        :'source_available' => :'Integer',
        :'source_warehouse_id' => :'String',
        :'suggested_quantity' => :'Integer',
        :'target_warehouse_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'max_stock',
        :'min_stock',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::ReplenishmentSuggestionLine` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::ReplenishmentSuggestionLine`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'current_stock')
        self.current_stock = attributes[:'current_stock']
      else
        self.current_stock = nil
      end

      if attributes.key?(:'max_stock')
        self.max_stock = attributes[:'max_stock']
      end

      if attributes.key?(:'min_stock')
        self.min_stock = attributes[:'min_stock']
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      else
        self.product_id = nil
      end

      if attributes.key?(:'product_name')
        self.product_name = attributes[:'product_name']
      else
        self.product_name = nil
      end

      if attributes.key?(:'sku')
        self.sku = attributes[:'sku']
      else
        self.sku = nil
      end

      if attributes.key?(:'source_available')
        self.source_available = attributes[:'source_available']
      else
        self.source_available = nil
      end

      if attributes.key?(:'source_warehouse_id')
        self.source_warehouse_id = attributes[:'source_warehouse_id']
      else
        self.source_warehouse_id = nil
      end

      if attributes.key?(:'suggested_quantity')
        self.suggested_quantity = attributes[:'suggested_quantity']
      else
        self.suggested_quantity = nil
      end

      if attributes.key?(:'target_warehouse_id')
        self.target_warehouse_id = attributes[:'target_warehouse_id']
      else
        self.target_warehouse_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @current_stock.nil?
        invalid_properties.push('invalid value for "current_stock", current_stock cannot be nil.')
      end

      if @product_id.nil?
        invalid_properties.push('invalid value for "product_id", product_id cannot be nil.')
      end

      if @product_name.nil?
        invalid_properties.push('invalid value for "product_name", product_name cannot be nil.')
      end

      if @sku.nil?
        invalid_properties.push('invalid value for "sku", sku cannot be nil.')
      end

      if @source_available.nil?
        invalid_properties.push('invalid value for "source_available", source_available cannot be nil.')
      end

      if @source_warehouse_id.nil?
        invalid_properties.push('invalid value for "source_warehouse_id", source_warehouse_id cannot be nil.')
      end

      if @suggested_quantity.nil?
        invalid_properties.push('invalid value for "suggested_quantity", suggested_quantity cannot be nil.')
      end

      if @target_warehouse_id.nil?
        invalid_properties.push('invalid value for "target_warehouse_id", target_warehouse_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @current_stock.nil?
      return false if @product_id.nil?
      return false if @product_name.nil?
      return false if @sku.nil?
      return false if @source_available.nil?
      return false if @source_warehouse_id.nil?
      return false if @suggested_quantity.nil?
      return false if @target_warehouse_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] current_stock Value to be assigned
    def current_stock=(current_stock)
      if current_stock.nil?
        fail ArgumentError, 'current_stock cannot be nil'
      end

      @current_stock = current_stock
    end

    # Custom attribute writer method with validation
    # @param [Object] product_id Value to be assigned
    def product_id=(product_id)
      if product_id.nil?
        fail ArgumentError, 'product_id cannot be nil'
      end

      @product_id = product_id
    end

    # Custom attribute writer method with validation
    # @param [Object] product_name Value to be assigned
    def product_name=(product_name)
      if product_name.nil?
        fail ArgumentError, 'product_name cannot be nil'
      end

      @product_name = product_name
    end

    # Custom attribute writer method with validation
    # @param [Object] sku Value to be assigned
    def sku=(sku)
      if sku.nil?
        fail ArgumentError, 'sku cannot be nil'
      end

      @sku = sku
    end

    # Custom attribute writer method with validation
    # @param [Object] source_available Value to be assigned
    def source_available=(source_available)
      if source_available.nil?
        fail ArgumentError, 'source_available cannot be nil'
      end

      @source_available = source_available
    end

    # Custom attribute writer method with validation
    # @param [Object] source_warehouse_id Value to be assigned
    def source_warehouse_id=(source_warehouse_id)
      if source_warehouse_id.nil?
        fail ArgumentError, 'source_warehouse_id cannot be nil'
      end

      @source_warehouse_id = source_warehouse_id
    end

    # Custom attribute writer method with validation
    # @param [Object] suggested_quantity Value to be assigned
    def suggested_quantity=(suggested_quantity)
      if suggested_quantity.nil?
        fail ArgumentError, 'suggested_quantity cannot be nil'
      end

      @suggested_quantity = suggested_quantity
    end

    # Custom attribute writer method with validation
    # @param [Object] target_warehouse_id Value to be assigned
    def target_warehouse_id=(target_warehouse_id)
      if target_warehouse_id.nil?
        fail ArgumentError, 'target_warehouse_id cannot be nil'
      end

      @target_warehouse_id = target_warehouse_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          current_stock == o.current_stock &&
          max_stock == o.max_stock &&
          min_stock == o.min_stock &&
          product_id == o.product_id &&
          product_name == o.product_name &&
          sku == o.sku &&
          source_available == o.source_available &&
          source_warehouse_id == o.source_warehouse_id &&
          suggested_quantity == o.suggested_quantity &&
          target_warehouse_id == o.target_warehouse_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [current_stock, max_stock, min_stock, product_id, product_name, sku, source_available, source_warehouse_id, suggested_quantity, target_warehouse_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
