=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class Shipment < ApiModelBase
    attr_accessor :delivered_at

    attr_accessor :label_url

    attr_accessor :line_items_shipment

    # References the order entity.
    attr_accessor :order_id

    attr_accessor :recipient_address

    attr_accessor :shipment_date

    attr_accessor :shipping_carrier

    attr_accessor :shipping_cost

    attr_accessor :shipping_method

    attr_accessor :signed_by

    attr_accessor :status

    # Latest carrier tracking events (from the live tracking API).
    attr_accessor :tracking_events

    attr_accessor :tracking_number

    attr_accessor :tracking_url

    attr_accessor :weight_kg

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'delivered_at' => :'deliveredAt',
        :'label_url' => :'labelUrl',
        :'line_items_shipment' => :'lineItemsShipment',
        :'order_id' => :'orderId',
        :'recipient_address' => :'recipientAddress',
        :'shipment_date' => :'shipmentDate',
        :'shipping_carrier' => :'shippingCarrier',
        :'shipping_cost' => :'shippingCost',
        :'shipping_method' => :'shippingMethod',
        :'signed_by' => :'signedBy',
        :'status' => :'status',
        :'tracking_events' => :'trackingEvents',
        :'tracking_number' => :'trackingNumber',
        :'tracking_url' => :'trackingUrl',
        :'weight_kg' => :'weightKg'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'delivered_at' => :'Time',
        :'label_url' => :'String',
        :'line_items_shipment' => :'Object',
        :'order_id' => :'String',
        :'recipient_address' => :'Object',
        :'shipment_date' => :'Date',
        :'shipping_carrier' => :'String',
        :'shipping_cost' => :'String',
        :'shipping_method' => :'String',
        :'signed_by' => :'String',
        :'status' => :'String',
        :'tracking_events' => :'Object',
        :'tracking_number' => :'String',
        :'tracking_url' => :'String',
        :'weight_kg' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'delivered_at',
        :'label_url',
        :'line_items_shipment',
        :'recipient_address',
        :'shipping_cost',
        :'shipping_method',
        :'signed_by',
        :'tracking_events',
        :'tracking_number',
        :'tracking_url',
        :'weight_kg'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::Shipment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::Shipment`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'delivered_at')
        self.delivered_at = attributes[:'delivered_at']
      end

      if attributes.key?(:'label_url')
        self.label_url = attributes[:'label_url']
      end

      if attributes.key?(:'line_items_shipment')
        self.line_items_shipment = attributes[:'line_items_shipment']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      else
        self.order_id = nil
      end

      if attributes.key?(:'recipient_address')
        self.recipient_address = attributes[:'recipient_address']
      end

      if attributes.key?(:'shipment_date')
        self.shipment_date = attributes[:'shipment_date']
      else
        self.shipment_date = nil
      end

      if attributes.key?(:'shipping_carrier')
        self.shipping_carrier = attributes[:'shipping_carrier']
      else
        self.shipping_carrier = nil
      end

      if attributes.key?(:'shipping_cost')
        self.shipping_cost = attributes[:'shipping_cost']
      end

      if attributes.key?(:'shipping_method')
        self.shipping_method = attributes[:'shipping_method']
      end

      if attributes.key?(:'signed_by')
        self.signed_by = attributes[:'signed_by']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'tracking_events')
        self.tracking_events = attributes[:'tracking_events']
      end

      if attributes.key?(:'tracking_number')
        self.tracking_number = attributes[:'tracking_number']
      end

      if attributes.key?(:'tracking_url')
        self.tracking_url = attributes[:'tracking_url']
      end

      if attributes.key?(:'weight_kg')
        self.weight_kg = attributes[:'weight_kg']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @order_id.nil?
        invalid_properties.push('invalid value for "order_id", order_id cannot be nil.')
      end

      if @shipment_date.nil?
        invalid_properties.push('invalid value for "shipment_date", shipment_date cannot be nil.')
      end

      if @shipping_carrier.nil?
        invalid_properties.push('invalid value for "shipping_carrier", shipping_carrier cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @order_id.nil?
      return false if @shipment_date.nil?
      return false if @shipping_carrier.nil?
      return false if @status.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] order_id Value to be assigned
    def order_id=(order_id)
      if order_id.nil?
        fail ArgumentError, 'order_id cannot be nil'
      end

      @order_id = order_id
    end

    # Custom attribute writer method with validation
    # @param [Object] shipment_date Value to be assigned
    def shipment_date=(shipment_date)
      if shipment_date.nil?
        fail ArgumentError, 'shipment_date cannot be nil'
      end

      @shipment_date = shipment_date
    end

    # Custom attribute writer method with validation
    # @param [Object] shipping_carrier Value to be assigned
    def shipping_carrier=(shipping_carrier)
      if shipping_carrier.nil?
        fail ArgumentError, 'shipping_carrier cannot be nil'
      end

      @shipping_carrier = shipping_carrier
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          delivered_at == o.delivered_at &&
          label_url == o.label_url &&
          line_items_shipment == o.line_items_shipment &&
          order_id == o.order_id &&
          recipient_address == o.recipient_address &&
          shipment_date == o.shipment_date &&
          shipping_carrier == o.shipping_carrier &&
          shipping_cost == o.shipping_cost &&
          shipping_method == o.shipping_method &&
          signed_by == o.signed_by &&
          status == o.status &&
          tracking_events == o.tracking_events &&
          tracking_number == o.tracking_number &&
          tracking_url == o.tracking_url &&
          weight_kg == o.weight_kg
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [delivered_at, label_url, line_items_shipment, order_id, recipient_address, shipment_date, shipping_carrier, shipping_cost, shipping_method, signed_by, status, tracking_events, tracking_number, tracking_url, weight_kg].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
