=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class StockMovement < ApiModelBase
    # Signed movement: positive = into stock, negative = out of stock.
    attr_accessor :delta

    # One of the `MOVEMENT_*` constants.
    attr_accessor :movement_type

    # References the product entity.
    attr_accessor :product_id

    # Absolute quantity moved (always >= 0).
    attr_accessor :quantity

    attr_accessor :reason

    # Primary-key of the referencing entity.
    attr_accessor :reference_id

    # Entity that caused the movement, e.g. `goods_receipt`, `stock_transfer`.
    attr_accessor :reference_type

    # References the warehouse entity.
    attr_accessor :warehouse_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'delta' => :'delta',
        :'movement_type' => :'movementType',
        :'product_id' => :'productId',
        :'quantity' => :'quantity',
        :'reason' => :'reason',
        :'reference_id' => :'referenceId',
        :'reference_type' => :'referenceType',
        :'warehouse_id' => :'warehouseId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'delta' => :'Integer',
        :'movement_type' => :'MovementType',
        :'product_id' => :'String',
        :'quantity' => :'Integer',
        :'reason' => :'String',
        :'reference_id' => :'String',
        :'reference_type' => :'ReferenceType',
        :'warehouse_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'reason',
        :'reference_id',
        :'reference_type',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::StockMovement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::StockMovement`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'delta')
        self.delta = attributes[:'delta']
      else
        self.delta = nil
      end

      if attributes.key?(:'movement_type')
        self.movement_type = attributes[:'movement_type']
      else
        self.movement_type = nil
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      else
        self.product_id = nil
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      else
        self.quantity = nil
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      end

      if attributes.key?(:'reference_id')
        self.reference_id = attributes[:'reference_id']
      end

      if attributes.key?(:'reference_type')
        self.reference_type = attributes[:'reference_type']
      end

      if attributes.key?(:'warehouse_id')
        self.warehouse_id = attributes[:'warehouse_id']
      else
        self.warehouse_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @delta.nil?
        invalid_properties.push('invalid value for "delta", delta cannot be nil.')
      end

      if @movement_type.nil?
        invalid_properties.push('invalid value for "movement_type", movement_type cannot be nil.')
      end

      if @product_id.nil?
        invalid_properties.push('invalid value for "product_id", product_id cannot be nil.')
      end

      if @quantity.nil?
        invalid_properties.push('invalid value for "quantity", quantity cannot be nil.')
      end

      if @warehouse_id.nil?
        invalid_properties.push('invalid value for "warehouse_id", warehouse_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @delta.nil?
      return false if @movement_type.nil?
      return false if @product_id.nil?
      return false if @quantity.nil?
      return false if @warehouse_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] delta Value to be assigned
    def delta=(delta)
      if delta.nil?
        fail ArgumentError, 'delta cannot be nil'
      end

      @delta = delta
    end

    # Custom attribute writer method with validation
    # @param [Object] movement_type Value to be assigned
    def movement_type=(movement_type)
      if movement_type.nil?
        fail ArgumentError, 'movement_type cannot be nil'
      end

      @movement_type = movement_type
    end

    # Custom attribute writer method with validation
    # @param [Object] product_id Value to be assigned
    def product_id=(product_id)
      if product_id.nil?
        fail ArgumentError, 'product_id cannot be nil'
      end

      @product_id = product_id
    end

    # Custom attribute writer method with validation
    # @param [Object] quantity Value to be assigned
    def quantity=(quantity)
      if quantity.nil?
        fail ArgumentError, 'quantity cannot be nil'
      end

      @quantity = quantity
    end

    # Custom attribute writer method with validation
    # @param [Object] warehouse_id Value to be assigned
    def warehouse_id=(warehouse_id)
      if warehouse_id.nil?
        fail ArgumentError, 'warehouse_id cannot be nil'
      end

      @warehouse_id = warehouse_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          delta == o.delta &&
          movement_type == o.movement_type &&
          product_id == o.product_id &&
          quantity == o.quantity &&
          reason == o.reason &&
          reference_id == o.reference_id &&
          reference_type == o.reference_type &&
          warehouse_id == o.warehouse_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [delta, movement_type, product_id, quantity, reason, reference_id, reference_type, warehouse_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
