=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class StockTransfer < ApiModelBase
    # JSON array of `{product_id, name, quantity, batch_number?}`.
    attr_accessor :line_items

    attr_accessor :notes

    # References the warehouse entity.
    attr_accessor :source_warehouse_id

    # One of: draft | completed | cancelled
    attr_accessor :status

    # References the warehouse entity.
    attr_accessor :target_warehouse_id

    attr_accessor :transfer_date

    attr_accessor :transfer_number

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'line_items' => :'lineItems',
        :'notes' => :'notes',
        :'source_warehouse_id' => :'sourceWarehouseId',
        :'status' => :'status',
        :'target_warehouse_id' => :'targetWarehouseId',
        :'transfer_date' => :'transferDate',
        :'transfer_number' => :'transferNumber'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'line_items' => :'Object',
        :'notes' => :'String',
        :'source_warehouse_id' => :'String',
        :'status' => :'StockTransferStatus',
        :'target_warehouse_id' => :'String',
        :'transfer_date' => :'Date',
        :'transfer_number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'line_items',
        :'notes',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::StockTransfer` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::StockTransfer`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'line_items')
        self.line_items = attributes[:'line_items']
      else
        self.line_items = nil
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end

      if attributes.key?(:'source_warehouse_id')
        self.source_warehouse_id = attributes[:'source_warehouse_id']
      else
        self.source_warehouse_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'target_warehouse_id')
        self.target_warehouse_id = attributes[:'target_warehouse_id']
      else
        self.target_warehouse_id = nil
      end

      if attributes.key?(:'transfer_date')
        self.transfer_date = attributes[:'transfer_date']
      else
        self.transfer_date = nil
      end

      if attributes.key?(:'transfer_number')
        self.transfer_number = attributes[:'transfer_number']
      else
        self.transfer_number = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @source_warehouse_id.nil?
        invalid_properties.push('invalid value for "source_warehouse_id", source_warehouse_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @target_warehouse_id.nil?
        invalid_properties.push('invalid value for "target_warehouse_id", target_warehouse_id cannot be nil.')
      end

      if @transfer_date.nil?
        invalid_properties.push('invalid value for "transfer_date", transfer_date cannot be nil.')
      end

      if @transfer_number.nil?
        invalid_properties.push('invalid value for "transfer_number", transfer_number cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @source_warehouse_id.nil?
      return false if @status.nil?
      return false if @target_warehouse_id.nil?
      return false if @transfer_date.nil?
      return false if @transfer_number.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] source_warehouse_id Value to be assigned
    def source_warehouse_id=(source_warehouse_id)
      if source_warehouse_id.nil?
        fail ArgumentError, 'source_warehouse_id cannot be nil'
      end

      @source_warehouse_id = source_warehouse_id
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] target_warehouse_id Value to be assigned
    def target_warehouse_id=(target_warehouse_id)
      if target_warehouse_id.nil?
        fail ArgumentError, 'target_warehouse_id cannot be nil'
      end

      @target_warehouse_id = target_warehouse_id
    end

    # Custom attribute writer method with validation
    # @param [Object] transfer_date Value to be assigned
    def transfer_date=(transfer_date)
      if transfer_date.nil?
        fail ArgumentError, 'transfer_date cannot be nil'
      end

      @transfer_date = transfer_date
    end

    # Custom attribute writer method with validation
    # @param [Object] transfer_number Value to be assigned
    def transfer_number=(transfer_number)
      if transfer_number.nil?
        fail ArgumentError, 'transfer_number cannot be nil'
      end

      @transfer_number = transfer_number
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          line_items == o.line_items &&
          notes == o.notes &&
          source_warehouse_id == o.source_warehouse_id &&
          status == o.status &&
          target_warehouse_id == o.target_warehouse_id &&
          transfer_date == o.transfer_date &&
          transfer_number == o.transfer_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [line_items, notes, source_warehouse_id, status, target_warehouse_id, transfer_date, transfer_number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
