=begin
#SimpleBilly API

#Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module SimplebillyApi
  class TicketMessage < ApiModelBase
    attr_accessor :author_email

    attr_accessor :author_name

    attr_accessor :body

    attr_accessor :body_html

    attr_accessor :channel_id

    attr_accessor :created_at

    attr_accessor :direction

    attr_accessor :external_id

    attr_accessor :is_internal

    attr_accessor :message_type

    attr_accessor :metadata

    attr_accessor :tenant_id

    # References the ticket entity.
    attr_accessor :ticket_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'author_email' => :'authorEmail',
        :'author_name' => :'authorName',
        :'body' => :'body',
        :'body_html' => :'bodyHtml',
        :'channel_id' => :'channelId',
        :'created_at' => :'createdAt',
        :'direction' => :'direction',
        :'external_id' => :'externalId',
        :'is_internal' => :'isInternal',
        :'message_type' => :'messageType',
        :'metadata' => :'metadata',
        :'tenant_id' => :'tenantId',
        :'ticket_id' => :'ticketId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'author_email' => :'String',
        :'author_name' => :'String',
        :'body' => :'String',
        :'body_html' => :'String',
        :'channel_id' => :'String',
        :'created_at' => :'Time',
        :'direction' => :'MessageDirection',
        :'external_id' => :'String',
        :'is_internal' => :'Boolean',
        :'message_type' => :'MessageType',
        :'metadata' => :'Object',
        :'tenant_id' => :'String',
        :'ticket_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'author_email',
        :'author_name',
        :'body_html',
        :'channel_id',
        :'external_id',
        :'metadata',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SimplebillyApi::TicketMessage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SimplebillyApi::TicketMessage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'author_email')
        self.author_email = attributes[:'author_email']
      end

      if attributes.key?(:'author_name')
        self.author_name = attributes[:'author_name']
      end

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      else
        self.body = nil
      end

      if attributes.key?(:'body_html')
        self.body_html = attributes[:'body_html']
      end

      if attributes.key?(:'channel_id')
        self.channel_id = attributes[:'channel_id']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'direction')
        self.direction = attributes[:'direction']
      else
        self.direction = nil
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'is_internal')
        self.is_internal = attributes[:'is_internal']
      else
        self.is_internal = nil
      end

      if attributes.key?(:'message_type')
        self.message_type = attributes[:'message_type']
      else
        self.message_type = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      else
        self.metadata = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'ticket_id')
        self.ticket_id = attributes[:'ticket_id']
      else
        self.ticket_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @body.nil?
        invalid_properties.push('invalid value for "body", body cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @direction.nil?
        invalid_properties.push('invalid value for "direction", direction cannot be nil.')
      end

      if @is_internal.nil?
        invalid_properties.push('invalid value for "is_internal", is_internal cannot be nil.')
      end

      if @message_type.nil?
        invalid_properties.push('invalid value for "message_type", message_type cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @ticket_id.nil?
        invalid_properties.push('invalid value for "ticket_id", ticket_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @body.nil?
      return false if @created_at.nil?
      return false if @direction.nil?
      return false if @is_internal.nil?
      return false if @message_type.nil?
      return false if @tenant_id.nil?
      return false if @ticket_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] body Value to be assigned
    def body=(body)
      if body.nil?
        fail ArgumentError, 'body cannot be nil'
      end

      @body = body
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] direction Value to be assigned
    def direction=(direction)
      if direction.nil?
        fail ArgumentError, 'direction cannot be nil'
      end

      @direction = direction
    end

    # Custom attribute writer method with validation
    # @param [Object] is_internal Value to be assigned
    def is_internal=(is_internal)
      if is_internal.nil?
        fail ArgumentError, 'is_internal cannot be nil'
      end

      @is_internal = is_internal
    end

    # Custom attribute writer method with validation
    # @param [Object] message_type Value to be assigned
    def message_type=(message_type)
      if message_type.nil?
        fail ArgumentError, 'message_type cannot be nil'
      end

      @message_type = message_type
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ticket_id Value to be assigned
    def ticket_id=(ticket_id)
      if ticket_id.nil?
        fail ArgumentError, 'ticket_id cannot be nil'
      end

      @ticket_id = ticket_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          author_email == o.author_email &&
          author_name == o.author_name &&
          body == o.body &&
          body_html == o.body_html &&
          channel_id == o.channel_id &&
          created_at == o.created_at &&
          direction == o.direction &&
          external_id == o.external_id &&
          is_internal == o.is_internal &&
          message_type == o.message_type &&
          metadata == o.metadata &&
          tenant_id == o.tenant_id &&
          ticket_id == o.ticket_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [author_email, author_name, body, body_html, channel_id, created_at, direction, external_id, is_internal, message_type, metadata, tenant_id, ticket_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
